export interface RoomRecipeList {
    name: string;
    number: string;  
    shortDesc: string;
    fullDesc: string;
    roomType: string;
  }
  
  export const ROOM_DATA: RoomRecipeList[] = [
    {number: '001', name: 'Basic Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '002', name: 'Social Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '003', name: 'Communal Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '004', name: 'Prepared Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '005', name: 'Farmers´ Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '006', name: 'Farmers´ Flophouse', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '007', name: 'Farmers´ Lodge', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '008', name: 'Dormitory', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '009', name: 'Done Up Dormitory', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '010', name: 'Luxury Dormitory', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '011', name: 'Basic Soldier´s Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '012', name: 'Barracks', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '013', name: 'Bigger Barracks', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bedroom'},
    {number: '014', name: 'Double Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '015', name: 'Private Men´s Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '016', name: 'Private Women´s Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '017', name: 'Rustic Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '018', name: 'Deluxe Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '019', name: 'Shower Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '020', name: 'Scenic Shower Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '021', name: 'Onsen Bathroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '022', name: '[NOT YET FOUND]', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '023', name: 'Swimming Pool', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bathroom'},
    {number: '024', name: 'Simple Kitchen', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '025', name: 'Kitchen Diner', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '026', name: 'Agricultural Kitchen', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '027', name: 'Agricultural Café', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '028', name: 'Simple Mushroom Cookroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '029', name: 'Deluxe Mushroom Kitchen', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '030', name: 'Simple Castle Kitchen', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '031', name: 'Castle Cafeteria', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '032', name: 'Gory Grillhouse', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '033', name: 'Standard Dining Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '034', name: 'King´s Dining Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Kitchen'},
    {number: '035', name: 'Private Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '036', name: 'Master Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '037', name: 'Private Noble´s Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '038', name: 'Rough n´ Tough Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '039', name: 'Neat n´ Sweet Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '040', name: 'Royal Bedchamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '041', name: 'Princess Bedchamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '042', name: 'Simple Shared Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '043', name: 'Superior Shared Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '044', name: 'Shared Noble Bedroom', shortDesc:'conteudo', fullDesc:'deded', roomType:'Private Bedroom'},
    {number: '045', name: 'Simple Bar', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bar'},
    {number: '046', name: 'Well-Stocked Bar', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bar'},
    {number: '047', name: 'Game Bar', shortDesc:'conteudo', fullDesc:'deded', roomType:'Bar'},
    {number: '048', name: 'Basic Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '049', name: 'Shared Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '050', name: 'Men´s Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '051', name: 'Women´s Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '052', name: 'Rustic Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '053', name: 'Lovely Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '054', name: 'Soldier´s Toilet', shortDesc:'conteudo', fullDesc:'deded', roomType:'Toilet'},
    {number: '055', name: 'Basic Changing Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Changing'},
    {number: '056', name: 'Spa Changing Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Changing'},
    {number: '057', name: 'Dancer´s Changing Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Changing'},
    {number: '058', name: 'Pool Changing Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Changing'},
    {number: '059', name: 'Living Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Changing'},
    {number: '060', name: 'Barn', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '061', name: 'Armory', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '062', name: 'Smithy', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '063', name: 'Metalworker´s Workshop', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '064', name: 'Brewery', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '065', name: 'Dyeing Workshop', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '066', name: 'Builder´s Workshop', shortDesc:'conteudo', fullDesc:'deded', roomType:'Workshop'},
    {number: '067', name: 'Item Store', shortDesc:'conteudo', fullDesc:'deded', roomType:'Shop'},
    {number: '068', name: 'Weapon Store', shortDesc:'conteudo', fullDesc:'deded', roomType:'Shop'},
    {number: '069', name: 'Reception', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '070', name: 'Corridor', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '071', name: 'Pumping Station', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '072', name: 'Relaxation Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '073', name: 'Chapel', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '074', name: 'War Room ', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '075', name: 'Wizard´s Workshop', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '076', name: 'Training Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '077', name: 'Throne Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '078', name: 'Shabby Throne Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '079', name: 'Chapel of The Children', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '080', name: 'Summoning Chamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '081', name: 'Creepy Conservatory', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '082', name: 'Study', shortDesc:'conteudo', fullDesc:'deded', roomType:'Miscelaneous'},
    {number: '083', name: 'Library', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '084', name: 'Sculpture Gallery', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '085', name: 'Picture Gallery', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '086', name: 'Large Museum Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '087', name: 'Small Exhibition Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '088', name: 'Large Exhibition Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '089', name: 'Small Treasury', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '090', name: 'Large Treasury', shortDesc:'conteudo', fullDesc:'deded', roomType:'Museum'},
    {number: '091', name: 'Graveyard', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '092', name: 'Fortune Teller Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '093', name: 'Mayor´s Office', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '094', name: 'Music Hall', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '095', name: 'Dance Hall', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '096', name: 'Prison Cell', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '097', name: 'Execution Chamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '098', name: 'Playroom/Toy Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '099', name: 'Slime Room [Secret Recipe]', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '100', name: 'Light Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '101', name: 'Lava Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '102', name: 'Dragonfly Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'More Miscelaneous'},
    {number: '103', name: 'Dragonlord´s Throne Room [REQUIRES A DQB1 SAVE FILE]', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '104', name: 'Demonlord´s Throne Room [Unlocks once you complete the Hargon Chapel, #079]', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '105', name: 'Pot Chamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '106', name: 'Mushroom Chamber', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '107', name: 'Wrecking Ball Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '108', name: 'Paddock', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '109', name: 'Animal House', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '110', name: 'Watering Hole', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '111', name: 'Well Room', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '112', name: 'Playful Park', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '113', name: 'Grassy Garden', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '114', name: 'Flower Garden', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '115', name: 'Luxurious Park', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '116', name: 'Tree Park', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '117', name: 'Cactus Garden [Do NOT plant cacti over 2 blocks high]', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '118', name: 'NOT FOUND YET', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '119', name: 'Stone Garden', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '120', name: 'Fountain Garden', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '121', name: 'Snow Garden', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '122', name: 'NOT YET FOUND', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'},
    {number: '123', name: 'NOT YET FOUND', shortDesc:'conteudo', fullDesc:'deded', roomType:'Special'}
  ];