export interface RoomRecipeList {
    name: string;
    number: string;  
    observation: string;
    roomType: string;
  }
  
  export const ROOM_LIST: RoomRecipeList[] = [
    {number: '001', name: 'Basic Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '002', name: 'Social Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '003', name: 'Communal Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '004', name: 'Prepared Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '005', name: 'Farmers´ Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '006', name: 'Farmers´ Flophouse', observation:'',  roomType:'Bedroom'},
    {number: '007', name: 'Farmers´ Lodge', observation:'',  roomType:'Bedroom'},
    {number: '008', name: 'Dormitory', observation:'',  roomType:'Bedroom'},
    {number: '009', name: 'Done Up Dormitory', observation:'',  roomType:'Bedroom'},
    {number: '010', name: 'Luxury Dormitory', observation:'',  roomType:'Bedroom'},
    {number: '011', name: 'Basic Soldier´s Bedroom', observation:'',  roomType:'Bedroom'},
    {number: '012', name: 'Barracks', observation:'',  roomType:'Bedroom'},
    {number: '013', name: 'Bigger Barracks', observation:'',  roomType:'Bedroom'},
    {number: '014', name: 'Double Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '015', name: 'Private Men´s Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '016', name: 'Private Women´s Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '017', name: 'Rustic Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '018', name: 'Deluxe Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '019', name: 'Shower Room', observation:'',  roomType:'Bathroom'},
    {number: '020', name: 'Scenic Shower Room', observation:'',  roomType:'Bathroom'},
    {number: '021', name: 'Onsen Bathroom', observation:'',  roomType:'Bathroom'},
    {number: '022', name: '[NOT YET FOUND]', observation:'',  roomType:'Bathroom'},
    {number: '023', name: 'Swimming Pool', observation:'',  roomType:'Bathroom'},
    {number: '024', name: 'Simple Kitchen', observation:'',  roomType:'Kitchen'},
    {number: '025', name: 'Kitchen Diner', observation:'',  roomType:'Kitchen'},
    {number: '026', name: 'Agricultural Kitchen', observation:'',  roomType:'Kitchen'},
    {number: '027', name: 'Agricultural Café', observation:'',  roomType:'Kitchen'},
    {number: '028', name: 'Simple Mushroom Cookroom', observation:'',  roomType:'Kitchen'},
    {number: '029', name: 'Deluxe Mushroom Kitchen', observation:'',  roomType:'Kitchen'},
    {number: '030', name: 'Simple Castle Kitchen', observation:'',  roomType:'Kitchen'},
    {number: '031', name: 'Castle Cafeteria', observation:'',  roomType:'Kitchen'},
    {number: '032', name: 'Gory Grillhouse', observation:'',  roomType:'Kitchen'},
    {number: '033', name: 'Standard Dining Room', observation:'',  roomType:'Kitchen'},
    {number: '034', name: 'King´s Dining Room', observation:'',  roomType:'Kitchen'},
    {number: '035', name: 'Private Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '036', name: 'Master Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '037', name: 'Private Noble´s Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '038', name: 'Rough n´ Tough Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '039', name: 'Neat n´ Sweet Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '040', name: 'Royal Bedchamber', observation:'',  roomType:'Private Bedroom'},
    {number: '041', name: 'Princess Bedchamber', observation:'',  roomType:'Private Bedroom'},
    {number: '042', name: 'Simple Shared Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '043', name: 'Superior Shared Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '044', name: 'Shared Noble Bedroom', observation:'',  roomType:'Private Bedroom'},
    {number: '045', name: 'Simple Bar', observation:'',  roomType:'Bar'},
    {number: '046', name: 'Well-Stocked Bar', observation:'',  roomType:'Bar'},
    {number: '047', name: 'Game Bar', observation:'',  roomType:'Bar'},
    {number: '048', name: 'Basic Toilet', observation:'',  roomType:'Toilet'},
    {number: '049', name: 'Shared Toilet', observation:'',  roomType:'Toilet'},
    {number: '050', name: 'Men´s Toilet', observation:'',  roomType:'Toilet'},
    {number: '051', name: 'Women´s Toilet', observation:'',  roomType:'Toilet'},
    {number: '052', name: 'Rustic Toilet', observation:'',  roomType:'Toilet'},
    {number: '053', name: 'Lovely Toilet', observation:'',  roomType:'Toilet'},
    {number: '054', name: 'Soldier´s Toilet', observation:'',  roomType:'Toilet'},
    {number: '055', name: 'Basic Changing Room', observation:'',  roomType:'Changing'},
    {number: '056', name: 'Spa Changing Room', observation:'',  roomType:'Changing'},
    {number: '057', name: 'Dancer´s Changing Room', observation:'',  roomType:'Changing'},
    {number: '058', name: 'Pool Changing Room', observation:'',  roomType:'Changing'},
    {number: '059', name: 'Living Room', observation:'',  roomType:'Changing'},
    {number: '060', name: 'Barn', observation:'',  roomType:'Workshop'},
    {number: '061', name: 'Armory', observation:'',  roomType:'Workshop'},
    {number: '062', name: 'Smithy', observation:'',  roomType:'Workshop'},
    {number: '063', name: 'Metalworker´s Workshop', observation:'',  roomType:'Workshop'},
    {number: '064', name: 'Brewery', observation:'',  roomType:'Workshop'},
    {number: '065', name: 'Dyeing Workshop', observation:'',  roomType:'Workshop'},
    {number: '066', name: 'Builder´s Workshop', observation:'',  roomType:'Workshop'},
    {number: '067', name: 'Item Store', observation:'',  roomType:'Shop'},
    {number: '068', name: 'Weapon Store', observation:'',  roomType:'Shop'},
    {number: '069', name: 'Reception', observation:'',  roomType:'Miscelaneous'},
    {number: '070', name: 'Corridor', observation:'',  roomType:'Miscelaneous'},
    {number: '071', name: 'Pumping Station', observation:'',  roomType:'Miscelaneous'},
    {number: '072', name: 'Relaxation Room', observation:'',  roomType:'Miscelaneous'},
    {number: '073', name: 'Chapel', observation:'',  roomType:'Miscelaneous'},
    {number: '074', name: 'War Room ', observation:'',  roomType:'Miscelaneous'},
    {number: '075', name: 'Wizard´s Workshop', observation:'',  roomType:'Miscelaneous'},
    {number: '076', name: 'Training Room', observation:'',  roomType:'Miscelaneous'},
    {number: '077', name: 'Throne Room', observation:'',  roomType:'Miscelaneous'},
    {number: '078', name: 'Shabby Throne Room', observation:'',  roomType:'Miscelaneous'},
    {number: '079', name: 'Chapel of The Children', observation:'',  roomType:'Miscelaneous'},
    {number: '080', name: 'Summoning Chamber', observation:'',  roomType:'Miscelaneous'},
    {number: '081', name: 'Creepy Conservatory', observation:'',  roomType:'Miscelaneous'},
    {number: '082', name: 'Study', observation:'',  roomType:'Miscelaneous'},
    {number: '083', name: 'Library', observation:'',  roomType:'Museum'},
    {number: '084', name: 'Sculpture Gallery', observation:'',  roomType:'Museum'},
    {number: '085', name: 'Picture Gallery', observation:'',  roomType:'Museum'},
    {number: '086', name: 'Large Museum Room', observation:'',  roomType:'Museum'},
    {number: '087', name: 'Small Exhibition Room', observation:'',  roomType:'Museum'},
    {number: '088', name: 'Large Exhibition Room', observation:'',  roomType:'Museum'},
    {number: '089', name: 'Small Treasury', observation:'',  roomType:'Museum'},
    {number: '090', name: 'Large Treasury', observation:'',  roomType:'Museum'},
    {number: '091', name: 'Graveyard', observation:'',  roomType:'More Miscelaneous'},
    {number: '092', name: 'Fortune Teller Room', observation:'',  roomType:'More Miscelaneous'},
    {number: '093', name: 'Mayor´s Office', observation:'',  roomType:'More Miscelaneous'},
    {number: '094', name: 'Music Hall', observation:'',  roomType:'More Miscelaneous'},
    {number: '095', name: 'Dance Hall', observation:'',  roomType:'More Miscelaneous'},
    {number: '096', name: 'Prison Cell', observation:'',  roomType:'More Miscelaneous'},
    {number: '097', name: 'Execution Chamber', observation:'',  roomType:'More Miscelaneous'},
    {number: '098', name: 'Playroom/Toy Room', observation:'',  roomType:'More Miscelaneous'},
    {number: '099', name: 'Slime Room', observation:'Secret Recipe',  roomType:'More Miscelaneous'},
    {number: '100', name: 'Light Room', observation:'',  roomType:'More Miscelaneous'},
    {number: '101', name: 'Lava Room', observation:'',  roomType:'More Miscelaneous'},
    {number: '102', name: 'Dragonfly Room', observation:'',  roomType:'More Miscelaneous'},
    {number: '103', name: 'Dragonlord´s Throne Room', observation:'Requires a DQB1 Save File',  roomType:'Special'},
    {number: '104', name: 'Demonlord´s Throne Room', observation:'Unlocks once you complete the Hargon Chapel, #079',  roomType:'Special'},
    {number: '105', name: 'Pot Chamber', observation:'',  roomType:'Special'},
    {number: '106', name: 'Mushroom Chamber', observation:'',  roomType:'Special'},
    {number: '107', name: 'Wrecking Ball Room', observation:'',  roomType:'Special'},
    {number: '108', name: 'Paddock', observation:'',  roomType:'Special'},
    {number: '109', name: 'Animal House', observation:'',  roomType:'Special'},
    {number: '110', name: 'Watering Hole', observation:'',  roomType:'Special'},
    {number: '111', name: 'Well Room', observation:'',  roomType:'Special'},
    {number: '112', name: 'Playful Park', observation:'',  roomType:'Special'},
    {number: '113', name: 'Grassy Garden', observation:'',  roomType:'Special'},
    {number: '114', name: 'Flower Garden', observation:'',  roomType:'Special'},
    {number: '115', name: 'Luxurious Park', observation:'',  roomType:'Special'},
    {number: '116', name: 'Tree Park', observation:'',  roomType:'Special'},
    {number: '117', name: 'Cactus Garden', observation:'Do NOT plant cacti over 2 blocks high',  roomType:'Special'},
    {number: '118', name: 'NOT FOUND YET', observation:'',  roomType:'Special'},
    {number: '119', name: 'Stone Garden', observation:'',  roomType:'Special'},
    {number: '120', name: 'Fountain Garden', observation:'',  roomType:'Special'},
    {number: '121', name: 'Snow Garden', observation:'',  roomType:'Special'},
    {number: '122', name: 'NOT YET FOUND', observation:'',  roomType:'Special'},
    {number: '123', name: 'NOT YET FOUND', observation:'',  roomType:'Special'}
  ];