
const menuLinks = [

  { location: '/rooms', name: 'Rooms', },
  { location: '/sets', name: 'Sets', },
  { location: '/combinations', name: 'Room Combinations' },
  { location: '/food', name: 'Food', },
  { location: '/materials', name: 'Materials' },
]

export function getLinks() {
  return menuLinks
}


export const roomList = [
  { name: "Basic Bedroom", type: "Inn", effects: "Residents will sleep in the beds.Note: Will create a Hotel when built next to a Reception Room.", requirements: "2 Bed (Any) 1 Light Source (Any)" },
  { name: "Social Bedroom", type: "Inn", effects: "Residents will sleep in the beds", requirements: "4 Bed (Any) 2 Light Source (Any)" },
  { name: "Communal Bedroom", type: "Inn", effects: "Residents will sleep in the beds", requirements: "8 Bed (Any) 4 Light Source (Any)" },
  { name: "Venerable Bedroom", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Bed (Any) 1 Light Source (Any) 1 Grandfather Clock or 1 Alarm Clock 1 Potted Flower (Set) or 1 Potted Plant (Set" },
  { name: "Farmers' Bedroom", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Farming Tools 1 Firewood 2 Bed (Any) 1 Light Source (Any)" },
  { name: "Farmers' Flophouse", type: "Inn", effects: "Residents will sleep in the beds", requirements: "2 Farming Tools 2 Firewood 4 Bed (Any) 2 Light Source (Any)" },
  { name: "Farmers' Lodge", type: "Inn", effects: "Residents will sleep in the beds", requirements: "4 Farming Tools 4 Firewood 8 Bed (Any) 4 Light Source (Any)" },
  { name: "Dormitory", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Inn Sign 3 Pot (Any) 8 Bed (Any)" },
  { name: "Done-up Dormitory", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Inn Sign 3 Pot (Any) 8 Bed (Any) 2 Light Source (Any) 2 Chair (Any)" },
  { name: "Drop-dead Dormitory", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Inn Sign 3 Pot (Any) 8 Fancy Bed (Any) 2 Fancy Light Source (Any) 2 Chair (Any) 1 Chest of Drawers" },
  { name: "Billet", type: "Inn", effects: "Residents will sleep in the beds", requirements: "1 Fighting Kit (Any) 2 Bed (Any) 1 Light Source (Any)" },
  { name: "Barracks", type: "Inn", effects: "Residents will sleep in the beds", requirements: "2 Fighting Kit (Any) 4 Bed (Any) 2 Light Source (Any)" },
  { name: "Garrison", type: "Inn", effects: "Residents will sleep in the beds", requirements: "4 Fighting Kit (Any) 8 Bed (Any) 4 Light Source (Any)" },
  { name: "Low-Lit Bedroom", type: "Inn", effects: "Residents will sleep in the beds(Requires the Hotto Stuff Pack DLC)", requirements: "2 Fancy Futon 1 Paper Lantern 1 Wardrobe or 1 Armoire or 1 Wooden Cabinet" },
  { name: "Low-Lit Hostel", type: "Inn", effects: "Residents will sleep in the beds(Requires the Hotto Stuff Pack DLC)", requirements: "4 Fancy Futon 2 Paper Lantern 1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 2 Lattice Wall" },
  { name: "Low-Lit Lodge", type: "Inn", effects: "Residents will sleep in the beds(Requires the Hotto Stuff Pack DLC)", requirements: "8 Fancy Futon 4 Paper Lantern 1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 4 Lattice Wall" },
  { name: "Waterlogged Bedroom", type: "Inn", effects: "Residents will sleep in the beds (requires the Aquarium Pack DLC)", requirements: "2 Bed (Any) 1 Seashell (Any) 1 Seaweed (Any) or 1 Starfish or 1 Coral or 1 Colossal Coral or 1 Anemone or 1 Pillar Collar" },
  { name: "Waterlogged Quarters", type: "Inn", effects: "Residents will sleep in the beds (requires the Aquarium Pack DLC)", requirements: "4 Bed (Any) 1 Seashell (Any) 1 Seaweed (Any) 1 Starfish or 1 Coral or 1 Colossal Coral or 1 Anemone or 1 Pillar Collar" },
  { name: "Waterlogged Lodging", type: "Inn", effects: "Residents will sleep in the beds (requires the Aquarium Pack DLC)", requirements: "8 Bed (Any) 1 Seashell (Any) 1 Seaweed (Any) 1 Starfish 1 Coral or 1 Colossal Coral or 1 Anemone or 1 Pillar Collar" },
  { name: "Contemporary Chamber", type: "Inn", effects: "Residents will sleep in the beds(Requires the Modernist Pack DLC)", requirements: "2 Bed (Any) 1 Light Source (Any) 1 Wooden Blind Headrail" },
  { name: "Contemporary Residence", type: "Inn", effects: "Residents will sleep in the beds(Requires the Modernist Pack DLC)", requirements: "4 Bed (Any) 2 Light Source (Any) 1 Wooden Blind Headrail 1 Sleek Shelf 1 Allarm Clock or 1 Grandfather Clock" },
  { name: "Contemporary Co-Living Pod", type: "Inn", effects: "", requirements: "8 Bed (Any) 2 Fancy Light Source (Any) 1 Wooden Blind Headrail 1 Sleek Shelf 1 Allarm Clock or 1 Grandfather Clock 1 Gramophone" },
  { name: "Shared Bathroom", type: "Bathroom", effects: "Residents will use the bathing facilities", requirements: "2 Basic Bathtub or 2 Bathtub or 2 Shower or 2 Bubbly Bath 2 Towel (Any) 2 Washtub 1 Light Source (Any)" },
  { name: "Men's Baths", type: "Bathroom", effects: "Residents will use the bathing facilities", requirements: "2 Basic Bathtub or 2 Bathtub or 2 Shower or 1 Spa (Set) or 2 Bubbly Bath 2 Towel (Any) 1 Gentleman Sign" },
  { name: "Ladies' Baths", type: "Bathroom", effects: "Residents will use the bathing facilities", requirements: "2 Basic Bathtub or 2 Bathtub or 2 Shower or 1 Spa (Set) or 2 Bubbly Bath 2 Towel (Any) 1 Lady Sign" },
  { name: "Rustic Bathroom", type: "Bathroom", effects: "Residents will bathe in the bathtub", requirements: "1 Basic Bathtub 3 Towel (Any) 4 Washtub 1 Chair (Any)" },
  { name: "Wood-burning Bathroom", type: "Bathroom", effects: "Residents will bathe in the bathtub", requirements: "2 Basic Bathtub 3 Towel (Any) 4 Washtub 1 Chair (Any) 1 Light Source (Any) 2 Firewood" },
  { name: "Shower Room", type: "Bathroom", effects: "Residents will use the shower", requirements: "1 Shower 1 Towel (Any) 1 Folding Screen" },
  { name: "Scenic Shower Room", type: "Bathroom", effects: "Residents will use showers.", requirements: "4 Shower 2 Towel (Any) 2 Folding Screen 2 Light Source (Any) 4 Small Window or 1 Window" },
  { name: "Steamy Spa", type: "Bathroom", effects: "Residents will bathe in the spa.Note: Will create a Spa Resort when built next to a Music Hall.", requirements: "1 Spa (Set) 1 Spa Spout 3 Bathing Stool 3 Washtub" },
  { name: "Suspicious Spa", type: "Bathroom", effects: "Residents will bathe in the plasma.", requirements: "10 Plasma 1 Evil Item (Any) 3 Bathing Stool 3 Washtub" },
  { name: "Sink 'n' Soak Bathroom", type: "Bathroom", effects: "Residents will bathe in the bathtub(Requires the Modernist Pack DLC)", requirements: "1 Basic Basin 1 Basic Bathtub or 1 Bathtub or 1 Shower or 1 Bubbly Bath 1 Towel (Any) 1 Light Source (Any)" },
  { name: "Pool of Paradise", type: "Bathroom", effects: "Residents will swim in the pool.", requirements: "1 Pool (Set) 1 Umbrella (Any) 1 Deckchair 1 Cactail" },
  { name: "Simple Kitchen", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.Note: Will create a Restaurant when built next to a Dining Room.", requirements: "1 Chest (Any) 3 Bonfire (Any) or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or [2 Bonfire (Any) and 1 Fiery Frying Pan (Set)" },
  { name: "Kitchen Diner", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.", requirements: "1 Chest (Any) 3 Bonfire (Any) or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or [2 Bonfire (Any) and 1 Fiery Frying Pan (Set)] 1 Dining Table (Set)" },
  { name: "Agricultural Kitchen", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.", requirements: "1 Chest (Any) 3 Sack of Wheat 2 Firewood 3 Bonfire (Any) or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or [2 Bonfire (Any) and 1 Fiery Frying Pan (Set)]" },
  { name: "Agricultural Cafe", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.", requirements: "1 Chest (Any) 3 Sack of Wheat 2 Firewood 3 Bonfire (Any) or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or [2 Bonfire (Any) and 1 Fiery Frying Pan (Set)] 1 Dining Table (Set)" },
  { name: "Mushroom Cookroom", type: "Kitchens", effects: "Residents will cook fungal foodstuffs.", requirements: "1 Chest (Any) 1 Fungus (Any) 2 Bonfire (Any) or 2 Fiery Frying Pan (Set) or [1 Bonfire (Any) and 1 Fiery Frying Pan (Set)]" },
  { name: "Toadstool Tearoom", type: "Kitchens", effects: "Residents will cook fungal foodstuffs.", requirements: "1 Chest (Any) 1 Fungus (Any) 2 Fiery Frying Pan (Set) or 1 Brick Barbecue 1 Dining Table (Set)" },
  { name: "Castle Kitchen", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.", requirements: "1 Chest (Any) 1 Well 1 Brick Barbecue or 2 Fiery Frying Pan (Set)" },
  { name: "Castle Cafeteria", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest.", requirements: "1 Chest (Any) 1 Well 1 Brick Barbecue or 2 Fiery Frying Pan (Set) 1 Buffet (Set)" },
  { name: "Gory Grillhouse", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest", requirements: "1 Chest (Any) 1 Meaty Marshy Mountain 1 Brick Barbecue" },
  { name: "Dining Room", type: "Kitchens", effects: "Note: Will create a Restaurant when built next to a Simple Kitchen.", requirements: "4 Dining Table (Set) 1 Light Source (Any)" },
  { name: "Banqueting Hall", type: "Kitchens", effects: "---", requirements: "1 Banqueting Table (Set) 2 Bold Banner or 2 Big Bold Banner 1 Fireplace" },
  { name: "Simple Scullery", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest(Requires the Hotto Stuff Pack DLC)", requirements: "1 Chest (Any) 2 Rice Sack 1 Stove 1 Pot (Any) 3 Bonfire or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or 2 Bonfire and 1 Fiery Frying Pan (Set)" },
  { name: "Luncheon Lounge", type: "Kitchens", effects: "(Requires the Hotto Stuff Pack DLC)", requirements: "1 Coffee Table or 1 Toasty Table 1 Confy Cushion 1 Decorative Food (Any)" },
  { name: "Sea-Salty Scullery", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest(Requires the Aquarium Pack DLC)", requirements: "1 Chest (Any) 1 Sink 1 Seashell (Any) 3 Bonfire or 2 Fiery Frying Pan (Set) or 1 Brick Barbecue or 2 Bonfire and 1 Fiery Frying Pan (Set)" },
  { name: "Oceanic Eatery", type: "Kitchens", effects: "(Requires the Aquarium Pack DLC)", requirements: "1 Seashell (Any) 1 Fountain (Any) 1 Dining Table (Set)" },
  { name: "Fitted Kitchen", type: "Kitchens", effects: "Residents will cook ingredients placed in the chest(Requires the Modernist Pack DLC)", requirements: "1 Kitchen Counter 1 Cooking Pot or 1 Frying Pan 1 Chopping Board 1 Chest (Any)" },
  { name: "Cultured Cafè", type: "Kitchens", effects: "(Requires the Modernist Pack DLC)", requirements: "1 Picture (Any) 2 Kaffe Täble 2 Chair (Any) 1 Decorative Food (Any) 1 Decorative Drink (Any) or the tables with the decorative item can be substituted with a Dining Table (Set) or Simple Sipper's Set (Set) respectively." },
  { name: "Private Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Resident's Sign (Any) 1 Bed (Any) 1 Light Source (Any) 1 Chair (Any)" },
  { name: "Master Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Resident's Sign (Any) 1 Bed (Any) 1 Light Source (Any) 1 Chair (Any) 1 Table (Any) 1 Wall Decoration (Any)" },
  { name: "Imperial Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Resident's Sign (Any) 1 Fancy Bed (Any) 1 Fancy Light Source (Any) 1 Fancy Chair (Any) 1 Fancy Table (Any) 1 Wall Decoration (Any)" },
  { name: "Rough n Tough Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Bed 1 Light Source 1 Set of Dumbbells 1 Barrel 1 Set of Bottles 1 Residents Sign" },
  { name: "Neat n Sweet Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Resident's Sign (Any) 1 Dressing Table 1 Chair (Any) 1 Ornamental Flower (Any) or 1 Potted Flower (Set) 1 Light Source (Any) 1 Bed (Any)" },
  { name: "Royal Bedchamber", type: "Private Rooms", effects: "Can be assigned as a resident's private room.Note: Will create a Castle when built next to a Throne Room.", requirements: "1 Resident's Sign (Any) 1 King-Sized Bed 1 Fancy Chair (Any) 1 Fancy Light Source (Any) 1 Fireplace" },
  { name: "Princess's Bedroom", type: "Private Rooms", effects: "Can be assigned as a resident's private room.", requirements: "1 Resident's Sign (Any) 1 Princess-Sized Bed 1 Fancy Chair (Any) 1 Fancy Light Source (Any) 1 Potted Flower (Set)" },
  { name: "Shared Room", type: "Private Rooms", effects: "Can be assigned as the private room of two residents of your choice.", requirements: "2 Resident's Sign (Any) 2 Bed (Any) 1 Light Source (Any) 2 Chair (Any)" },
  { name: "Superior Shared Room", type: "Private Rooms", effects: "Can be assigned as the private room of two residents of your choice.", requirements: "2 Resident's Sign (Any) 2 Bed (Any) 1 Light Source (Any) 2 Chair (Any) 1 Table (Any) 1 Wall Decoration (Any)" },
  { name: "Stupendous Shared Room", type: "Private Rooms", effects: "Can be assigned as the private room of two residents of your choice.", requirements: "2 Resident's Sign (Any) 2 Fancy Bed (Any) 1 Fancy Light Source (Any) 2 Fancy Chair (Any) 1 Fancy Table (Any) 1 Wall Decoration (Any)" },
  { name: "Basic Bar", type: "Bars", effects: "Bartenders will serve drinks to residents.", requirements: "1 Cocktail Counter (Set)" },
  { name: "Well-stocked Bar", type: "Bars", effects: "Bartenders will serve drinks to residents.", requirements: "1 Cocktail Counter (Set) 1 Pub Sign 2 Simple Sipper's Set (Set) 1 Social Sippers' Set (Set) 2 Cask" },
  { name: "Party Pub", type: "Bars", effects: "Bartenders will serve drinks to residents.", requirements: "1 Cocktail Counter (Set) 1 Pub Sign 1 Water Jug 1 Card Table (Set) 1 Darty Party (Set) 1 Wall-Mounted Light Source (Any)" },
  { name: "Toilet", type: "Toilets", effects: "Residents will use the toilet.", requirements: "1 Pot (Any) or 1 Wooden Toilet 1 Towel (Any)" },
  { name: "Public Toilet", type: "Toilets", effects: "Residents will use the toilets.", requirements: "3 Wooden Toilet 3 Towel (Any) 2 Folding Screen" },
  { name: "Men's Toilet", type: "Toilets", effects: "Residents will use the toilets.", requirements: "3 Wooden Toilet 3 Towel (Any) 1 Gentlemen Sign" },
  { name: "Ladies' Toilet", type: "Toilets", effects: "Residents will use the toilets.", requirements: "3 Wooden Toilet 3 Towel (Any) 1 Lady Sign" },
  { name: "Rustic Toilet", type: "Toilets", effects: "Residents will use the toilet.", requirements: "1 Pot (Any) or 1 Wooden Toilet 1 Towel (Any) 1 Haystack" },
  { name: "Sweet-smelling Toilet", type: "Toilets", effects: "Residents will use the toilet.", requirements: "1 Pot (Any) or 1 Wooden Toilet 1 Towel (Any) 1 Ornamental Flower (Any) or 1 Potted Flower (Set)" },
  { name: "Chivalrous Toilet", type: "Toilets", effects: "Residents will use the toilet.", requirements: "1 Pot (Any) or 1 Wooden Toilet 1 Towel (Any) 1 Wall-Mounted Banner" },
  { name: "Clogged Bog", type: "Toilets", effects: "(Requires the Hotto Stuff Pack DLC)", requirements: "1 Pot (Any) or 1 Wooden Toilet 1 Towel (Any) 1 Sandals" },
  { name: "Changing Room", type: "Changing Rooms", effects: "Residents will change into outfits placed in the wardrobe.", requirements: "1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 1 Light Source (Any) 1 Dressing Table 1 Chair (Any)" },
  { name: "Spa Changing Room", type: "Changing Rooms", effects: "Residents will change into bath towels.", requirements: "1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 1 Light Source (Any) 1 Towel (Any) 1 Washtub" },
  { name: "Dancer's Changing Room", type: "Changing Rooms", effects: "Residents will change into cottontail costumes.", requirements: "1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 1 Light Source (Any) 1 Barrel 1 Ornamental Flower (Any) or 1 Potted Flower (Set)" },
  { name: "Pool Changing Room", type: "Changing Rooms", effects: "Residents will change into scandalous swimsuits.", requirements: "1 Wardrobe or 1 Armoire or 1 Wooden Cabinet 1 Light Source (Any) 1 Towel (Any) 1 Sunbrella or 1 Chic Sunbrella" },
  { name: "Chill-out Room", type: "Changing Rooms", effects: "---", requirements: "1 Comfy Sofa or 2 Left-Armed Couch or 1 Söfå or 1 Classy Couch 2 Potted Flower (Set) 2 Potted Plant (Set) 1 Fireplace 1 Swabbing Tools" },
  { name: "Barn", type: "Workshops", effects: "Residents will put items in the chest.", requirements: "1 Chest (Any) 1 Pot (Any) 1 Haystack 1 Rope 1 Farming Tools 1 Firewood" },
  { name: "Armoury", type: "Workshops", effects: "Residents will equip weapons placed in the chest.", requirements: "1 Chest (Any) 4 Fighting Kit (Any) 2 Barricade" },
  { name: "Smithy", type: "Workshops", effects: "Certain residents will make items.", requirements: "1 Forge or 1 Furnace 1 Chest (Any) 1 Hanging Bag (Any) 1 Pot (Any)" },
  { name: "Armourer's Workshop", type: "Workshops", effects: "no effect", requirements: "1 Anvil 1 Chest (Any) 1 Hanging bag (Any) 1 Armourer's Sign" },
  { name: "Potable Plant", type: "Workshops", effects: "Certain residents will make drinks.", requirements: "2 Cask 1 Chest (Any) 1 Hanging Bag (Any) 2 Barrel" },
  { name: "Dyeworks", type: "Workshops", effects: "Certain residents will make dye.", requirements: "1 Stain Extractor 1 Chest (Any) 1 Hanging Bag (Any) 2 Washtub" },
  { name: "Builder's Workshop", type: "Workshops", effects: "---", requirements: "1 Builder's Workbench 1 Chest (Any) 1 Hanging Bag (Any) 1 Medicinal Mortar 1 Cooking Utensils" },
  { name: "Item Shop", type: "Merchants", effects: "Merchants will sell items.Note: In order to use the Ornamental Medial Herb or the Ornamental Chimaera Wing, it is required to have either used a preorder bonus code or to have bought the digital Switch version with season pass included.", requirements: "1 Table (Any) 1 Price Tag 1 Shop Sign 2 Crate (Any) or 1 Ornamental Medical Herb or 1 Ornamental Chimaera Wing" },
  { name: "Armourer's Shop", type: "Merchants", effects: "Merchants will sell equipment.", requirements: "1 Table (Any) 1 Price Tag 1 Armourer's Sign 2 Fighting Kit (Any)" },
  { name: "Souvenir Shop", type: "Merchants", effects: "Merchants will sell items. (requires the Aquarium Pack DLC) Note: Will create a Sealife Center when built next to an Aquarium Room.", requirements: "1 Table (Any) 1 Prize Tag 1 Slime Balloons 1 Marine Monument or 1 Merman Model or 1 Healix the Hero" },
  { name: "Reception Room", type: "Social Spaces", effects: "Note: Will create a Hotel when built next to a Basic Bedroom.", requirements: "2 Table (Any) 1 Wall Decoration (Any) 1 Tabletop Light Source (Any) 1 Stationary" },
  { name: "Hallway", type: "Social Spaces", effects: "---", requirements: "2 Light Sources (Any) 2 Column (Any) 2 Ornamental Flower (Any) or 2 Potted Flower (Set) 2 Wall Decoration (Any) or 2 Curtain (Any) or 2 Bold Banner or 2 Big Bold Banner" },
  { name: "Porch", type: "Social Spaces", effects: "(Requires the Modernist Pack DLC)", requirements: "1 High Heels or 1 Sandals 1 Ornamental Flower (Any) 1 Display Hook or 1 Display Frame" },
  { name: "Wheelhouse", type: "Social Spaces", effects: "(Requires the Hotto Stuff Pack DLC)", requirements: "1 Waterwheel 1 Hanging Bag (Any) 1 Rice Sack or 1 Sack of Wheat or 1 Firewood or 1 Anvil or 1 Stain Extractor" },
  { name: "Pumping Station", type: "Social Spaces", effects: "---", requirements: "2 Dumb-Bells 2 Mining Tools 2 Towel (Any)" },
  { name: "Relaxation Room", type: "Social Spaces", effects: "Gives you a timely stat boost!Note: if the room has a Cheecky atmosphere dancer residents will offer a Buff-Buff massage.", requirements: "1 Bed (Any) 2 Curtain (Any) 1 Folding Screen 1 Light Source (Any)" },
  { name: "Meditation Station", type: "Social Spaces", effects: "(Requires the Hotto Stuff Pack DLC)", requirements: "1 Hanging Picture 1 Samurai Sword Collection 1 Carved Mural" },
  { name: "Stylish Study", type: "Social Spaces", effects: "(Requires the Modernist Pack DLC)", requirements: "1 Table (Any) 1 Chair (Any) 1 Book (Any) 1 Sleek Shelf 1 Gramophone" },
  { name: "Chapel", type: "Social Spaces", effects: "Nuns will worship at the altar.", requirements: "1 Altar 2 Tabletop Light Source (Any) 1 Goddess Statue 4 Chair (Any)" },
  { name: "War Room", type: "Social Spaces", effects: "Certain residents will engage in strategy meetings.", requirements: "1 Emblematic Table 1 Map 2 Wargame Piece (Any)" },
  { name: "Wizard's Workshop", type: "Social Spaces", effects: "Some residents will make items.", requirements: "1 Wizard's Workbench 1 Crystal Ball 1 Comfy Cushion 1 Incense Burner" },
  { name: "Training Room", type: "Social Spaces", effects: "Soldiers will undergo training.", requirements: "4 Target Dummy 2 Ornamental Spears 4 Wooden Fortification" },
  { name: "Dojo", type: "Social Spaces", effects: "Soldiers will undergo training.(Requires the Hotto Stuff Pack DLC)", requirements: "2 Target Dummy 1 Hanging Picture 1 Samurai Sword Collection" },
  { name: "Throne Room", type: "Social Spaces", effects: "Only the monarch can use the room's contents.Note: Will create a Castle when built next to a Royal Bedchamber.", requirements: "1 Throne 4 Bold Banner or 4 Big Bold Banner 2 Brazier" },
  { name: "Shabby Throne Room", type: "Social Spaces", effects: "---", requirements: "1 Disfigured Throne" },
  { name: "Chapel of the Children", type: "Social Spaces", effects: "---", requirements: "1 Unholy Altar 1 False Idol 1 Citadel Cross Carving 1 Citadel Creature Carving 1 Fiendish Face 1 Sinister Sconce" },
  { name: "Summoning Chamber", type: "Social Spaces", effects: "Certain residents will use the forbidden altar to make items.", requirements: "1 Forbidden Altar 1 Chest (Any) 1 False Idol 2 Peculiar Pillar 1 Unholy Altar 1 Sinister Sconce" },
  { name: "Creepy Conservatory", type: "Social Spaces", effects: "Residents will put items in the chest.", requirements: "1 Chest (Any) 2 Blooming Poxglove 4 Budding Poxglove" },
  { name: "Study Room", type: "Social Spaces", effects: "---", requirements: "3 Bookcase 3 Biblio-pile or 3 Reading Material (Any)" },
  { name: "Library", type: "Social Spaces", effects: "---", requirements: "5 Bookcase 3 Biblio-pile 3 Reading Material (Any) 1 Table (Any) 1 Chair (Any) 1 Note" },
  { name: "Sculpture Gallery", type: "Museums", effects: "---", requirements: "1 Stationary Statue or 1 Statue (Any) 3 Handrail (Any)" },
  { name: "Art Gallery", type: "Museums", effects: "---", requirements: "2 Picture (Any) 4 Handrail (Any)" },
  { name: "Exhibition Room", type: "Museums", effects: "---", requirements: "4 Picture (Any) 2 Statue (Any) 10 Handrail (Any) 1 Fancy Signpost" },
  { name: "Miniture Museum", type: "Museums", effects: "---", requirements: "2 Display Stand (Any) 4 Handrail (Any)" },
  { name: "Monumental Museum", type: "Museums", effects: "---", requirements: "5 Display Stand (Any) 10 Handrail (Any) 1 Fancy Signpost 2 Shelf" },
  { name: "Treasury", type: "Museums", effects: "---", requirements: "1 Display Stand (Any) 2 Handrail (Any) 5 Treasure Chest 1 Treasure (Any)" },
  { name: "Treasure House", type: "Museums", effects: "---", requirements: "1 Display Stand (Any) 2 Handrail (Any) 5 Treasure Chest 1 Treasure (Any) 1 Treasure Pile 2 Bold Banner or 2 Big Bold Banner" },
  { name: "Aquarium", type: "Museums", effects: "(requires the Aquarium Pack DLC) Note: Will create a Sealife Center when built next to an Souvenir Shop Room.", requirements: "1 Fish Tank (Set) 1 Fancy Signpost 1 Porthole or 1 Viewing Dome" },
  { name: "Graveyard", type: "Miscellaneous", effects: "no effect", requirements: "3 Memorial (Any) 3 Flower (Any) 1 Bench (Any)" },
  { name: "Diviner's Den", type: "Miscellaneous", effects: "---", requirements: "1 Crystal Ball 1 Comfy Cushion 1 Biblio-Pile 1 Reading Material (Any) 2 Curtain (Any)" },
  { name: "Town Hall", type: "Miscellaneous", effects: "no effect", requirements: "1 Residents' Register 1 Bell 3 Small Table (Any) 1 Signpost or 1 Fat Rat Signpost" },
  { name: "Music Hall", type: "Miscellaneous", effects: "Certain residents will sing at night.Note: Will create a Spa Resort when built next to a Steamy Spa.", requirements: "3 Instrument (Any) or [1 Playable Piano (Set) and 2 Instrument (Any)] 1 Chair (Any) 2 Curtain (Any)" },
  { name: "Dance Hall", type: "Miscellaneous", effects: "Dancers will sometimes perform on the boogie boards.", requirements: "3 Boogie Board 1 Light Box 4 Curtain (Any)" },
  { name: "Cell", type: "Miscellaneous", effects: "---", requirements: "1 Chains 1 Pot (Any)" },
  { name: "Torture Chamber", type: "Miscellaneous", effects: "---", requirements: "2 Chains 1 Guillotine 1 Straw Mattress 2 Bones (Any)" },
  { name: "Play Room", type: "Miscellaneous", effects: "---", requirements: "2 Cuddly Toy (Any) 1 Powie Yowie Rug 1 Chair (Any)" },
  { name: "Illumination Station", type: "Miscellaneous", effects: "---", requirements: "1 Bench (Any) 2 Ceramic Sconce 2 Sconce 2 Brazier 2 Watchfire" },
  { name: "Magma Chamber", type: "Miscellaneous", effects: "---", requirements: "6 Liquid Lava 3 Small Stone (Any) or 2 Large Stone (Any) or 1 Enormous Stone (Any)" },
  { name: "Swamp", type: "Miscellaneous", effects: "---", requirements: "6 Muddy Water 3 Reeds 1 Tainted Tree" },
  { name: "Wet Room", type: "Miscellaneous", effects: "(requires the Aquarium Pack DLC)", requirements: "10 Water (pure, muddy, sea, hot) 2 Porthole or 2 Viewing Dome 3 Seaweed (Any) 1 Basalt Blob" },
  { name: "Hargon's Throne Room", type: "Miscellaneous", effects: "---", requirements: "1 Hargon's Throne 2 Peculiar Pillar 2 Banner of Hargon" },
  { name: "Pot Chamber", type: "Miscellaneous", effects: "Residents will put items in the chest.", requirements: "5 Pot (Any) 1 Chest (Any)" },
  { name: "Marsh-room", type: "Miscellaneous", effects: "Residents will put fungi in the chest.", requirements: "6 Fungus (Any) 1 Chest (Any)" },
  { name: "Doomed Room", type: "Miscellaneous", effects: "---", requirements: "1 Wrecking Ball" },
  { name: "Paddock", type: "Gardens", effects: "---", requirements: "5 Wheatgrass 1 Wooden Gate or 1 Picket Gate or 1 Saloon Door 1 Haystack" },
  { name: "Animal House", type: "Gardens", effects: "Can make animals happier.Note: Room can have pets assigned to it with a Resident's Sign (Any). Will create a Petting Zoo when built next to a Playful Park.", requirements: "1 Pet Bedding 1 Pet Bowl 1 Haystack" },
  { name: "Watering Hole", type: "Gardens", effects: "---", requirements: "10 Pure Water 1 Chest (Any) 1 Washtub 2 Pot (Any)" },
  { name: "Fishing Hole", type: "Gardens", effects: "Gillian, Finn and Elder class residents will fish inside it (the types of fish catched depends on the kind of water used)(Requires the Aquarium Pack DLC)", requirements: "1 Fish Cage (Set) 1 Washtub 1 Rubber Ring 1 Rope" },
  { name: "Well Room", type: "Gardens", effects: "---", requirements: "1 Wooden Doormat or 1 Stone Doormat (doormat must be placed where the door to the room would be) 1 Well 1 Flower (Any)" },
  { name: "Playful Park", type: "Gardens", effects: "Note: Will create a Petting Zoo when built next to an Animal House.", requirements: "1 Bench (Any) 1 Tree Swing (Set) 2 Flower (Any) 2 Plank Pathway" },
  { name: "Grassy Garden", type: "Gardens", effects: "---", requirements: "1 Bench (Any) 5 Plant (Any)" },
  { name: "Flower Garden", type: "Gardens", effects: "---", requirements: "6 Flower (Any) 4 Plant (Any)" },
  { name: "Botanical Garden", type: "Gardens", effects: "---", requirements: "1 Fancy Bench 8 Milkblossom (any 8 same-colored milkblossom-like flowers will work) 1 Rose 1 Rose Leaves 1 Hydrangea" },
  { name: "Arboretum", type: "Gardens", effects: "---", requirements: "1 Bench 1 Big Plumberry Tree 1 Big Palm Tree 1 Big Ceder Tree or 1 Big Snowy Cedar Tree 1 Big Silver Birch Tree 2 Branch" },
  { name: "Cactus Garden", type: "Gardens", effects: "Note: Online reports say cacti must not be stacked higher than two block height.", requirements: "1 Bench 3 Prickly Peach Cactus 2 Cactus Crown 3 Cactus Trunk 1 Gladiolus 1 Sunflowers" },
  { name: "Tropical Garden", type: "Gardens", effects: "---", requirements: "1 Simple Bench 1 Pongsettia 1 Bigonia 5 Tingleweed 1 Fan Fern 1 Coneconut Tree" },
  { name: "Rockery", type: "Gardens", effects: "---", requirements: "1 Bench 3 Big Rock or 3 Mossy Rock 5 Small Stones or 5 Mossy Stones 1 Pebble Pile 2 Stepping Stones" },
  { name: "Fountain Foyer", type: "Gardens", effects: "---", requirements: "1 Fancy Bench 10 Pure Water 1 Fountain (Any) 1 Water Lily Flower 1 Lily Pad" },
  { name: "Winter Garden", type: "Gardens", effects: "---", requirements: "1 Bench 1 Snowman 3 Freezia 2 Snowy Cedar or 2 Big Snowy Cedar" },
  { name: "Freak-out Room", type: "Gardens", effects: "---", requirements: "1 Simple Bench 1 Vile Tile 2 Huge Horn 3 Septic Shrub 2 Dead Tree 3 Pampas Grass" },
  { name: "Cantlin Garden", type: "Gardens", effects: "---", requirements: "1 Fancy Bench 5 Holyhock 3 Blossoming Shrub 1 Cherry Blossom Tree 8 Pure Water 1 Basic Bridge" },
  { name: "Elegant Garden", type: "Gardens", effects: "(Requires the Hotto Stuff Pack DLC)", requirements: "1 Stone Lantern 1 Indefinite Donking Device 1 Pine Tree (any) or 1 Bamboo (any) or 1 Cherry Blossom Tree" },
  { name: "Slimy Room", type: "Secret Rooms", effects: "Note: In order to unlock the Stackable Slime, it is required to have either a preorder bonus code or to have bought the digital Switch version with season pass included.", requirements: "2 Slimy Eye 1 Slimy Mouth 1 Slime Light 1 Stackable Slime" },
  { name: "Dragonlord's Throne Room", type: "Secret Rooms", effects: "Note: Requires a Dragon Quest Builders save file to be present in the system and to have used Claim Builder Bonus in the title screen to unlock the Dragonlord's Throne.", requirements: "1 Dragonlord's Throne 2 Draconic Column 2 Dragonlord's Standard" }
]

export const setsList = [
  { name: "Fiery Frying Pan", requirement: "1 Frying Pan, 1 Bonfire", effect: "Allows for cooking of two ingredients together.Placement: Frying pan must be placed on top of the bonfire." },
  { name: "Dining Table", requirement: "1 Table (Any), 1 Chair (Any), 1 Decorative Food (Any)", effect: "Placement: Decorative food must be placed on top of the table." },
  { name: "Buffet", requirement: "[1 Big Table and 1 Crockery] or 1 Decorative Food (Any) and [2 Small Table (Any) or 1 Long Table (Any) or 2 Large Table (Any) or 1 Fancy Table (Any) or 1 Bar Counter], 1 Crock Pot", effect: "Nuns will serve food to residents.Placement: Crock pot and decorative food or crockery must be placed on top of the table." },
  { name: "Banqueting Table", requirement: "1 Royal Dining Table, 4 Decorative Food (Any) or 1 Three-Course Meal (Set), 2 Candlestick, 4 Fancy Chair (Any)", effect: "Placement: Decorative food must be placed on top of the table." },
  { name: "Three-course Meal", requirement: "1 Soup and Salad Set, 1 Fish Dish or 1 Meat Feast or 1 Deep-Fried Feast or 1 Supersized Steak Set, 1 Bread Basket, 1 Decorative Food (Any drink-type)", effect: "Note: Only drink-type decorations accepted (e.g. a Full Flagon or a Cactail)." },
  { name: "Spa", requirement: "10 Hot Water, 1 Floating Flower Petals or 1 Fierce Fountain", effect: "Residents will bathe in the water." },
  { name: "Pool", requirement: "10 Pure Water, 1 Ladder", effect: "Residents will swim in the water." },
  { name: "Cocktail Counter", requirement: "1 Bar Counter or 4 Small Table (Any) or 2 Long Table (Any) or 1 Large Table, 4 Chair (Any), 1 Cocktail Shaker", effect: "Bartenders will serve drinks to residents.Placement: Table must be placed adjacent to chairs." },
  { name: "Simple Sipper's Set", requirement: "1 Table (Any), 1 Chair (Any), 1 Decorative Food (Any drink-type)", effect: "Dancing girls and boys will serve drinks to residents.Placement: Drinks must be placed on top of the table." },
  { name: "Social Sipper's Set", requirement: "4 Chair (Any), 1 Large Table (Any) or 2 Long Table (Any) or 4 Small Table (Any) or 1 Fancy Table (Any), 4 Decorative Food (Any drink-type)", effect: "Placement: Table must be adjacent to chairs and drinks must be on top of the tables." },
  { name: "Card Table", requirement: "1 Playing Cards, 1 Table (Any), 2 Chair (Any)", effect: "Placement: Cards must be on top of the table and table must be adjacent to chairs." },
  { name: "Medication Station", requirement: "1 Chair (Any), 1 First Aid Kit, 1 Crate", effect: "Soldiers will heal the wounded." },
  { name: "Rocket Battery", requirement: "3 Firework Cannon", effect: "Residents will launch fireworks." },
  { name: "Dracky Stack", requirement: "3 Stackable Dracky (Any)", effect: "Placement: 3 Stackable Drackies (of any type) must be placed on top of each other." },
  { name: "Slime Stack", requirement: "3 Stackable Slime (Any)", effect: "Placement: the 3 Slimes must be placed on top of each other.Note: In order to unlock the Stackable Slime, it is required to have either a preorder bonus code or to have bought the digital Switch version with season pass included." },
  { name: "Tree Swing", requirement: "1 Swing, 1 Tree (Any)", effect: "-" },
  { name: "Potted Flower", requirement: "1 Plant Pot or 1 Planter or 1 Hexagonal Planter, 1 Flower (Any)", effect: "Placement: Flower must be placed on top of planter." },
  { name: "Potted Plant", requirement: "1 Plant Pot or 1 Planter or 1 Hexagonal Planter, 1 Plant (Any)", effect: "Placement: Plant must be placed on top of planter." },
  { name: "Station", requirement: "1 Track (Any), 1 Stop Sign", effect: "-" },
  { name: "Darty Party", requirement: "3 Dartboard", effect: "-" },
  { name: "Playable Piano", requirement: "1 Grand Piano, 1 Chair (Any)", effect: "Residents will play the piano." },
  { name: "Fisherman's Cookfire", requirement: "Bonfire (any), Flame-Grilled Fish", effect: "Resident will cook (requires the Aquarium Pack DLC)" },
  { name: "Fish Cage", requirement: "1 Netting, 10 Water (pure, muddy, sea, hot)", effect: "Gillian, Finn and Elder class residents will fish inside (the types of fish catched depends of the kind of water used)(Requires the Aquarium Pack DLC)" },
  { name: "Fish Tank", requirement: "4 Small Window, 10 Water (pure, muddy, sea, hot)", effect: "Residents admire the fish inside producing gratitude (Requires the Aquarium Pack DLC)" },
  { name: "Celebratory Cedar", requirement: "1 Gift-Wrapped Gift, 1 Cedar-type tree (any kind)", effect: "(Requires the Modernist pack DLC)" }
]

export const combinationsList = [
  { name: "Restaurant", requirement: "1 Simple Kitchen room, 1 Dining Room room", effect: "A round plate with a fork and a spoon crossed above it" },
  { name: "Hotel", requirement: "1 Reception room, 1 Basic Bedroom room", effect: "A square with a bed in the center" },
  { name: "Petting Zoo", requirement: "1 Playful Park room, 1 Animal House room", effect: "A shield-like emblem with the head of a spotted cow on it" },
  { name: "Spa Resort", requirement: "1 Steamy Spa room, 1 Music Hall room", effect: "A stylized spa logo, featuring an half circle with three steam streams above it" },
  { name: "Sealife Center", requirement: "1 Aquarium room, 1 Souvenir Shop room", effect: "A shield-like emblem with a fish and a coral branch on it(Requires the Aquarium Pack DLC)" },
  { name: "Castle", requirement: "1 Throne Room room, 1 Royal Bedchamber room", effect: "A stylized castle" }
]

export const foodList = [
  { name: "Grilled Greens", type: "Kitchen", requirement: "Vegetable (1)", hunger: "20", hp: "10", effect: "" },
  { name: "Great Grilled Greens", type: "Kitchen", requirement: "Vegetable (2)", hunger: "25", hp: "10", effect: "" },
  { name: "Gorgeous Grilled Greens", type: "Kitchen", requirement: "Vegetable (3)", hunger: "30", hp: "10", effect: "" },
  { name: "Seared Steak", type: "Kitchen", requirement: "Meat (1)", hunger: "30", hp: "5", effect: "Attack Up" },
  { name: "Superior Steak", type: "Kitchen", requirement: "Meat (2)", hunger: "35", hp: "5", effect: "Attack Up" },
  { name: "Spectacular Steak", type: "Kitchen", requirement: "Meat (3)", hunger: "40", hp: "5", effect: "Attack Up" },
  { name: "Fish Stick", type: "Kitchen", requirement: "Fish (1)", hunger: "25", hp: "5", effect: "Defense Up" },
  { name: "Fine Fish Stick", type: "Kitchen", requirement: "Fish (2)", hunger: "30", hp: "5", effect: "Defense Up" },
  { name: "Finest Fish Stick", type: "Kitchen", requirement: "Fish (3)", hunger: "35", hp: "5", effect: "Defense Up" },
  { name: "Bread", type: "Kitchen", requirement: "Wheat", hunger: "30", hp: "5", effect: "" },
  { name: "Fruit Flambé", type: "Kitchen", requirement: "Fruit (1)", hunger: "10", hp: "15", effect: "" },
  { name: "Fine Fruit Flambé", type: "Kitchen", requirement: "Fruit (2)", hunger: "15", hp: "15", effect: "" },
  { name: "Finest Fruit Flambé", type: "Kitchen", requirement: "Fruit (3)", hunger: "20", hp: "15", effect: "" },
  { name: "Shrooms on a Stick", type: "Kitchen", requirement: "Mushroom", hunger: "20", hp: "10", effect: "Destruction Up" },
  { name: "Spectacular Shrooms on a Stick", type: "Kitchen", requirement: "Glumgus", hunger: "30", hp: "10", effect: "Destruction Up" },
  { name: "Crispy Kelp", type: "Kitchen", requirement: "Kelp", hunger: "15", hp: "10", effect: "" },
  { name: "Seared Scallywinkle", type: "Kitchen", requirement: "Scallywinkle", hunger: "20", hp: "10", effect: "" },
  { name: "Cactus Steak", type: "Kitchen", requirement: "Cactus Cutlet", hunger: "20", hp: "10", effect: "" },
  { name: "Jacket Potato", type: "Kitchen", requirement: "Potato", hunger: "25", hp: "10", effect: "" },
  { name: "Corn on the Cob", type: "Kitchen", requirement: "Sweetcorn", hunger: "25", hp: "10", effect: "" },
  { name: "Boiled Butterbeans", type: "Kitchen", requirement: "Butterbeans", hunger: "20", hp: "10", effect: "" },
  { name: "Fried Egg", type: "Kitchen", requirement: "Egg", hunger: "20", hp: "10", effect: "Attack Up" },
  { name: "Sweeties", type: "Kitchen", requirement: "Sugar Cane", hunger: "5", hp: "15", effect: "" },
  { name: "Flame Grilled Plumberry", type: "Kitchen", requirement: "Plumberry", hunger: "20", hp: "10", effect: "Attack Up" },
  { name: "Cooked Crab Claw", type: "Kitchen", requirement: "Crab Claw", hunger: "20", hp: "10", effect: "Defense Up" },
  { name: "Hot Milk", type: "Kitchen", requirement: "Milk", hunger: "5", hp: "15", effect: "Confusion Immunity" },
  { name: "Tentagllatelle", type: "Kitchen", requirement: "Vile Vines", hunger: "20", hp: "20", effect: "" },
  { name: "Slimy Steak", type: "Kitchen", requirement: "Manky Meat", hunger: "30", hp: "10", effect: "Attack Up" },
  { name: "Butter", type: "Kitchen", requirement: "Milk, Oil", hunger: "5", hp: "5", effect: "" },
  { name: "Stir-Fry", type: "Kitchen", requirement: "Vegetable (1), Meat (1)", hunger: "30", hp: "15", effect: "Attack Up" },
  { name: "Superior Stir-Fry", type: "Kitchen", requirement: "Vegetable (2), Meat (1)", hunger: "35", hp: "15", effect: "Attack Up" },
  { name: "Spectacular Stir-Fry", type: "Kitchen", requirement: "Vegetable (3), Meat (2)", hunger: "45", hp: "15", effect: "Attack Up" },
  { name: "Slime Bun", type: "Kitchen", requirement: "Grain (1), Meat (1)", hunger: "35", hp: "10", effect: "Attack Up" },
  { name: "Superior Slime Bun", type: "Kitchen", requirement: "Grain (1), Meat (2)", hunger: "40", hp: "10", effect: "Attack Up" },
  { name: "Turf 'N' Truff", type: "Kitchen", requirement: "Meat (1), Fungus (1)", hunger: "45", hp: "15", effect: "Destruction Up" },
  { name: "Tastier Turf 'N' Truff", type: "Kitchen", requirement: "Meat (2), Fungus (1)", hunger: "50", hp: "15", effect: "Destruction Up" },
  { name: "Tastiest Turf 'N' Truff", type: "Kitchen", requirement: "Meat (3), Fungus (2)", hunger: "60", hp: "15", effect: "Destruction Up" },
  { name: "Seafood Salad", type: "Kitchen", requirement: "Vegetable (1), Fish (1)", hunger: "30", hp: "20", effect: "Defense Up" },
  { name: "Superior Seafood Salad", type: "Kitchen", requirement: "Vegetable (3), Fish (1)", hunger: "35", hp: "20", effect: "Defense Up" },
  { name: "Spectacular Seafood Salad", type: "Kitchen", requirement: "Vegetable (3), Fish (3)", hunger: "45", hp: "20", effect: "Defense Up" },
  { name: "Fish Bowl", type: "Kitchen", requirement: "Fish (1), Grain (1)", hunger: "45", hp: "15", effect: "Defense Up" },
  { name: "Fine Fish Bowl", type: "Kitchen", requirement: "Fish (3), Grain (1)", hunger: "50", hp: "15", effect: "Defense Up" },
  { name: "Saucy Spaghetti", type: "Kitchen", requirement: "Vegetable (1), Grain (1)", hunger: "40", hp: "10", effect: "" },
  { name: "Superior Saucy Spaghetti", type: "Kitchen", requirement: "Vegetable (2), Grain (1)", hunger: "45", hp: "10", effect: "" },
  { name: "Fruit Pie", type: "Kitchen", requirement: "Grain (1), Fruit (1)", hunger: "25", hp: "15", effect: "" },
  { name: "Fine Fruit Pie", type: "Kitchen", requirement: "Grain (1), Fruit (2)", hunger: "30", hp: "15", effect: "" },
  { name: "Fries", type: "Kitchen", requirement: "Oil, Potato", hunger: "25", hp: "10", effect: "" },
  { name: "Scrumptious Salad", type: "Kitchen", requirement: "Cabbage, Tomato", hunger: "30", hp: "25", effect: "" },
  { name: "Scrumptiouser Salad", type: "Kitchen", requirement: "Red Cabbage, Killer Tomato", hunger: "40", hp: "25", effect: "" },
  { name: "Pumpkin Soup", type: "Kitchen", requirement: "Pumpkin, Milk", hunger: "25", hp: "20", effect: "" },
  { name: "Superior Pumpkin Soup", type: "Kitchen", requirement: "Plumpkin, Milk", hunger: "30", hp: "20", effect: "" },
  { name: "Pumpkin Pie", type: "Kitchen", requirement: "Pumpkin, Grain (1)", hunger: "35", hp: "20", effect: "" },
  { name: "Superior Pumpkin Pie", type: "Kitchen", requirement: "Plumpkin, Grain (1)", hunger: "40", hp: "20", effect: "" },
  { name: "Buttermilk", type: "Kitchen", requirement: "Butterbeans, Pure Water", hunger: "5", hp: "20", effect: "" },
  { name: "Supersized Steak", type: "Kitchen", requirement: "Scaly Steak, Beef", hunger: "65", hp: "15", effect: "Attack Up" },
  { name: "Schnitzel", type: "Kitchen", requirement: "Meat (1), Oil", hunger: "35", hp: "10", effect: "Attack Up" },
  { name: "Searing Steak", type: "Kitchen", requirement: "Meat (1), Chili Pepper", hunger: "40", hp: "10", effect: "Attack Up" },
  { name: "Superior Searing Steak", type: "Kitchen", requirement: "Meat (1), Red-Hot Chili Pepper", hunger: "45", hp: "10", effect: "Attack Up" },
  { name: "Fried Fish", type: "Kitchen", requirement: "Fish (1), Oil", hunger: "30", hp: "10", effect: "Defense Up" },
  { name: "Pizza", type: "Kitchen", requirement: "Grain (1), Cheese", hunger: "55", hp: "20", effect: "" },
  { name: "Buttered Toast", type: "Kitchen", requirement: "Butter, Grain (1)", hunger: "30", hp: "15", effect: "" },
  { name: "Pancake", type: "Kitchen", requirement: "Wheat, Egg", hunger: "40", hp: "15", effect: "" },
  { name: "Rice Pudding", type: "Kitchen", requirement: "Grain (1), Milk", hunger: "30", hp: "10", effect: "" },
  { name: "Cream of Marshroom Soup", type: "Kitchen", requirement: "Fungus (1), Buttermilk", hunger: "30", hp: "15", effect: "Destruction Up" },
  { name: "Coddled Egg", type: "Kitchen", requirement: "Egg, Hot Water", hunger: "15", hp: "5", effect: "Attack Up" },
  { name: "Gungerbread", type: "Kitchen", requirement: "Grain (1), Sugar Cane", hunger: "10", hp: "20", effect: "" },
  { name: "Ice Cream", type: "Kitchen", requirement: "Snow, Milk", hunger: "10", hp: "15", effect: "" },
  { name: "Snow Cone", type: "Kitchen", requirement: "Fruit (1), Ice", hunger: "10", hp: "20", effect: "" },
  { name: "Chop Gooey", type: "Kitchen", requirement: "Vile Vines, Manky Meat", hunger: "50", hp: "35", effect: "Attack Up" },
  { name: "Soldier's Stew", type: "Kitchen", requirement: "Vegetable (1), Meat (1), Pure Water", hunger: "60", hp: "15", effect: "Attack Up" },
  { name: "Superior Soldier's Stew", type: "Kitchen", requirement: "Vegetable (2), Meat (2), Pure Water", hunger: "70", hp: "15", effect: "Attack Up" },
  { name: "Spectacular Soldier's Stew", type: "Kitchen", requirement: "Vegetable (3), Meat (3), Pure Water", hunger: "80", hp: "15", effect: "Attack Up" },
  { name: "Burger", type: "Kitchen", requirement: "Meat (1), Grain (1), Vegetable (1)", hunger: "65", hp: "15", effect: "Attack Up" },
  { name: "Better Burger", type: "Kitchen", requirement: "Meat (2), Grain (1), Vegetable (2)", hunger: "75", hp: "15", effect: "Attack Up" },
  { name: "Sailor's Stew", type: "Kitchen", requirement: "Vegetable (1), Fish (1), Pure Water", hunger: "55", hp: "25", effect: "Defense Up" },
  { name: "Superior Sailor's Stew", type: "Kitchen", requirement: "Vegetable (2), Fish (1), Pure Water", hunger: "65", hp: "25", effect: "Defense Up" },
  { name: "Spectacular Sailor's Stew", type: "Kitchen", requirement: "Vegetable (3), Fish (3), Pure Water", hunger: "75", hp: "25", effect: "Defense Up" },
  { name: "Crabby Croquette", type: "Kitchen", requirement: "Crab, Grain (1), Milk", hunger: "45", hp: "20", effect: "Defense Up" },
  { name: "Potato Salad", type: "Kitchen", requirement: "Potato, Aubergette, Egg", hunger: "30", hp: "25", effect: "" },
  { name: "Cheeseburger", type: "Kitchen", requirement: "Cheese, Meat (1), Grain (1)", hunger: "75", hp: "20", effect: "Attack Up" },
  { name: "Meat Mountain", type: "Kitchen", requirement: "Beef, Lamb Chop, Chicken Drumsticks", hunger: "100", hp: "10", effect: "Attack Up" },
  { name: "Bouillabaisse", type: "Kitchen", requirement: "Fish (1), Tomato, Pure Water", hunger: "65", hp: "25", effect: "Defense Up" },
  { name: "Better Bouillabaisse", type: "Kitchen", requirement: "Fish (1), Killer Tomato, Pure Water", hunger: "75", hp: "25", effect: "Defense Up" },
  { name: "Cheesy Risotto", type: "Kitchen", requirement: "Grain (1), Cheese, Butter", hunger: "65", hp: "20", effect: "" },
  { name: "Porridge", type: "Kitchen", requirement: "Grain (1), Leek, Pure Water", hunger: "30", hp: "10", effect: "" },
  { name: "Fungoulash", type: "Kitchen", requirement: "Marshrooms, Frogstool, Glumgus", hunger: "55", hp: "10", effect: "Destruction Up" },
  { name: "Butterbean Broth", type: "Kitchen", requirement: "Butterbean Butter, Leek, Pure Water", hunger: "5", hp: "35", effect: "" },
  { name: "Fruity Tart", type: "Kitchen", requirement: "Fruit (1), Grain (1), Sugar Cane", hunger: "25", hp: "15", effect: "" },
  { name: "Hearty Cream Cake", type: "Kitchen", requirement: "Grain (1), Sugar Cane, Strawberry", hunger: "25", hp: "20", effect: "" },
  { name: "Heartier Cream Cake", type: "Kitchen", requirement: "Grain (1), Sugar Cane, Moreberry", hunger: "35", hp: "20", effect: "" },
  { name: "Sponge Cake", type: "Kitchen", requirement: "Grain (1), Sugar Cane, Butterbean", hunger: "30", hp: "20", effect: "" },
  { name: "Whitebait", type: "Kitchen", requirement: "Wheat, Fish (1), Oil", hunger: "25", hp: "25", effect: "Defense Up" },
  { name: "Fish Meunière", type: "Kitchen", requirement: "Fish (1), Grain (1), Butter", hunger: "35", hp: "10", effect: "Swim Speed Up" },
  { name: "Fish and Chips", type: "Kitchen", requirement: "Fish (1), Potato, Oil", hunger: "30", hp: "15", effect: "Swim Speed Up" },
  { name: "Goregasbord", type: "Kitchen", requirement: "Vile Vines, Manky Meat, Frogstool", hunger: "80", hp: "50", effect: "Attack Up" },
  { name: "Full Moon Gungerbread", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, Chili Pepper", hunger: "15", hp: "20", effect: "Paralysis Immunity" },
  { name: "Fine Full Moon Gungerbread", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, Red-Hot Chili Pepper", hunger: "25", hp: "20", effect: "Paralysis Immunity" },
  { name: "Gungerbread of Awakening", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, Coffee Bean", hunger: "15", hp: "20", effect: "Sleep Immunity" },
  { name: "Gungerbread of Immunity", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, Heatroot", hunger: "15", hp: "20", effect: "Poison Immunity" },
  { name: "Good Gungerbread of Immunity", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, White-Hot Heatroot", hunger: "25", hp: "20", effect: "Poison Immunity" },
  { name: "Gungerbread of Clarity", type: "Kitchen", requirement: "Grain (1), Medicine Leaf, Leek", hunger: "15", hp: "20", effect: "Confusion Immunity" },
  { name: "Diggers Jigger", type: "Cask", requirement: "Fruit (1)", hunger: "", hp: "", effect: "" },
  { name: "Prickly Pop", type: "Cask", requirement: "Prickly Peach", hunger: "", hp: "", effect: "" },
  { name: "Savoury Smoothie", type: "Cask", requirement: "Vegetable (1)", hunger: "", hp: "", effect: "" },
  { name: "Black Coffee", type: "Cask", requirement: "Coffee Beans", hunger: "", hp: "", effect: "" },
  { name: "Pickled Heatroot", type: "Cask", requirement: "Heatroot", hunger: "", hp: "", effect: "" },
  { name: "Cheese", type: "Cask", requirement: "Milk", hunger: "", hp: "", effect: "" },
  { name: "Butterbean Butter", type: "Cask", requirement: "Butterbean", hunger: "", hp: "", effect: "" },
  { name: "Butter", type: "Cask", requirement: "Milk, Oil", hunger: "", hp: "", effect: "" },
  { name: "Springtide Sprinkles", type: "Miscellaneous ", requirement: "Cherry Blossom", hunger: "", hp: "", effect: "Changes nearby trees into cherry blossom trees." },
  { name: "Monster Munchies", type: "Miscellaneous ", requirement: "Frogstool, Dry Grass", hunger: "", hp: "", effect: "Present it to a weakened monster to recruit them." }
]

export const materialList = [
  {name: "Humus", island: "Soggy Skerry", obt: "Yes", location: "Earth Hills"},
{name: "Big Plumberry Tree", island: "Soggy Skerry", obt: "-", location: "Hills"},
{name: "Plumberry Tree", island: "Soggy Skerry", obt: "-", location: "Hills, Dock"},
{name: "Plumberry Stump", island: "Soggy Skerry", obt: "-", location: "Hills, (broken Plumberry Tree)"},
{name: "Big Withered Tree", island: "Soggy Skerry", obt: "-", location: "On Leafy Spoiled Soil (Forests)"},
{name: "Withered Tree", island: "Soggy Skerry", obt: "-", location: "On Leafy Spoiled Soil"},
{name: "Bark", island: "Soggy Skerry", obt: "Yes", location: "Greenery block forests"},
{name: "Blocky Buttress Root", island: "Soggy Skerry", obt: "-", location: "Greenery block forests"},
{name: "Blocky Branch", island: "Soggy Skerry", obt: "-", location: "Greenery block forests"},
{name: "Blocky Root", island: "Soggy Skerry", obt: "-", location: "Greenery block forests"},
{name: "Leaves", island: "Soggy Skerry", obt: "Yes", location: "Greenery block forests"},
{name: "Acorn", island: "Soggy Skerry", obt: "-", location: "Greenery block forests"},
{name: "Wheat", island: "Soggy Skerry", obt: "-", location: "Earth Hills, Tilled Soil"},
{name: "Aubergette", island: "Soggy Skerry", obt: "-", location: "Greenery forests, Planting Pole"},
{name: "Hydrangea", island: "Soggy Skerry", obt: "-", location: "Found on sides of Earth/Grassy Earth hills"},
{name: "Chicken", island: "Soggy Skerry", obt: "-", location: "Livestock"},
{name: "Swampy Soil", island: "Soggy Skerry", obt: "-", location: "Swamps"},
{name: "Leafy Spoiled Soil", island: "Soggy Skerry", obt: "-", location: "Greenery"},
{name: "Mossy Earth", island: "Soggy Skerry", obt: "-", location: "Earth Hills, Dock"},
{name: "Dry Ivy", island: "Soggy Skerry", obt: "-", location: "On sides of Mountains"},
{name: "Reeds", island: "Soggy Skerry", obt: "-", location: "In muddy water (swamp)"},
{name: "Pestilential Nest", island: "Soggy Skerry", obt: "-", location: "On Swampland (Swampy Soil)/Spoiled Soil"},
{name: "Mossy Stones", island: "Soggy Skerry", obt: "-", location: "Greenery Forests"},
{name: "Mossy Rock", island: "Soggy Skerry", obt: "-", location: "Greenery Forests"},
{name: "Bramble", island: "Soggy Skerry", obt: "Yes", location: "Swamp, on Swampy Soil"},
{name: "Big Bramble", island: "Soggy Skerry", obt: "Yes", location: "Swamp, on Swampy Soil"},
{name: "Pumpkin", island: "Soggy Skerry", obt: "-", location: "Greenery, on Tilled Soil."},
{name: "Gangrenous Greenery", island: "Soggy Skerry", obt: "-", location: "Found on Swamplands/Spoiled Soil"},
{name: "Sandwort", island: "Soggy Skerry", obt: "-", location: "Mossy Greenery"},
{name: "Spleenwort", island: "Soggy Skerry", obt: "-", location: "Leafy Greenery"},
{name: "Glowdrop", island: "Soggy Skerry", obt: "Yes", location: "Greenery block forests."},
{name: "Fiddleheads", island: "Soggy Skerry", obt: "-", location: "Greenery, near block forests."},
{name: "Villager (F)", island: "Soggy Skerry", obt: "-", location: "-"},
{name: "Villager (M)", island: "Soggy Skerry", obt: "-", location: "-"},
{name: "Villager (F)", island: "Soggy Skerry", obt: "-", location: "-"},
{name: "Villager (M)", island: "Soggy Skerry", obt: "-", location: "-"},
{name: "Earth", island: "Blossom Bay", obt: "Yes", location: "Meadow (below), Dock"},
{name: "Grassy Earth", island: "Blossom Bay", obt: "-", location: "Meadow, Dock"},
{name: "Lumpy Umber", island: "Blossom Bay", obt: "Yes", location: "Umber Hills"},
{name: "Umber", island: "Blossom Bay", obt: "Yes", location: "Umber Hills"},
{name: "Grass", island: "Blossom Bay", obt: "-", location: "Meadows, Dock"},
{name: "Milkblossom", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadows (generally large areas). No butterflies."},
{name: "Milkblossom", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadows (generally large areas). Butterflies"},
{name: "Daffodaisy", island: "Blossom Bay", obt: "-", location: "Earth (often near water)"},
{name: "Coralily", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadows (generally large areas)"},
{name: "Emeraldahila", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadows, near sea?"},
{name: "Ultramarose", island: "Blossom Bay", obt: "-", location: "Top of Chalk mountains"},
{name: "Ivy", island: "Blossom Bay", obt: "-", location: "Sides of (Umber) Hills"},
{name: "Cabbage", island: "Blossom Bay", obt: "-", location: "Near Meadow Trees, Tilled Earth"},
{name: "Tomato", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadows (generally large areas), Planting Pole."},
{name: "Dog", island: "Blossom Bay", obt: "-", location: "Pet"},
{name: "Cherry Blossom Tree", island: "Blossom Bay", obt: "-", location: "Rare Tree, Near Umbral Hills (or use Springtide Sprinkles)"},
{name: "Big Plumberry Tree", island: "Blossom Bay", obt: "-", location: "Meadow or Forest"},
{name: "Plumberry Tree", island: "Blossom Bay", obt: "-", location: "Meadow or Forest, Dock"},
{name: "Plumberry Stump", island: "Blossom Bay", obt: "-", location: "Limegrassy Earth Forests"},
{name: "Branch", island: "Blossom Bay", obt: "-", location: "Meadow"},
{name: "Pristine Plumberry", island: "Blossom Bay", obt: "-", location: "Near Plumberry Trees"},
{name: "Beastly Burrow", island: "Blossom Bay", obt: "-", location: "Limegrassy Earth Forests"},
{name: "Strawberry", island: "Blossom Bay", obt: "-", location: "Limegrassy Earth Meadows"},
{name: "Sugar Cane", island: "Blossom Bay", obt: "-", location: "In Lakes, Tilled Earth"},
{name: "Wheatgrass", island: "Blossom Bay", obt: "-", location: "Grassy Earth Meadow (generally large area)"},
{name: "Medicinal Shrub", island: "Blossom Bay", obt: "-", location: "Meadow"},
{name: "Stalwort", island: "Blossom Bay", obt: "-", location: "Limegrassy Earth Forests"},
{name: "Lily Pad", island: "Blossom Bay", obt: "-", location: "In Lakes"},
{name: "Large Lily Pad", island: "Blossom Bay", obt: "-", location: "In Lakes"},
{name: "Water Lily Flower", island: "Blossom Bay", obt: "-", location: "In Lakes"},
{name: "Buckwheat", island: "Blossom Bay", obt: "Buckwheat Seeds", location: "Hard to identify at first, appears similar to grass, but more spikey"},
{name: "Farmer (F)", island: "Blossom Bay", obt: "-", location: "-"},
{name: "Farmer (M)", island: "Blossom Bay", obt: "-", location: "-"},
{name: "Earth", island: "Iridescent Island", obt: "Yes", location: "Found on the docks near the tree or hills with Coal"},
{name: "Light Dolomite", island: "Iridescent Island", obt: "Yes", location: "Found on the docks or on the upper Green/Red Dye section of Dolomite spires."},
{name: "Dark Dolomite", island: "Iridescent Island", obt: "Yes", location: "Found near the beach or in the Gold/Silver section of Dolomite spires"},
{name: "Copper Vein", island: "Iridescent Island", obt: "-", location: "Found in hills with Clay"},
{name: "Clay", island: "Iridescent Island", obt: "Yes", location: "Found in hills with Copper"},
{name: "Clodstone", island: "Iridescent Island", obt: "-", location: "Often found near Earth and Dolomite"},
{name: "Chalk", island: "Iridescent Island", obt: "Yes", location: "Found on the docks"},
{name: "Chunky Chalk", island: "Iridescent Island", obt: "Yes", location: "Found on Chalk Mountains"},
{name: "Obsidian", island: "Iridescent Island", obt: "-", location: "Primarily found near the bottom of spires and hills or Zenithium and Ruby Spires"},
{name: "Red Dye Vein", island: "Iridescent Island", obt: "-", location: "Found in the upper Light Dolomite section of Silver/Red Dye Spires."},
{name: "Ruby Vein", island: "Iridescent Island", obt: "-", location: "Found in the upper sections of Zenithium/Ruby/Obsidian Spires"},
{name: "Zenithium Vein", island: "Iridescent Island", obt: "-", location: "Found in the lower section of Zenithium/Ruby/Obsidian Spires"},
{name: "Coffee Beans", island: "Iridescent Island", obt: "-", location: "Found on Earth hills without Coal, but with Obsidian."},
{name: "Frogstool", island: "Iridescent Island", obt: "-", location: "Found on Earth near sea level."},
{name: "Silver Vein", island: "Iridescent Island", obt: "-", location: "Found in the Dark Dolomite part of Silver/Red Dye Spires"},
{name: "Green Dye Vein-", island: "Iridescent Island", obt: "-", location: "Found in the Light Dolomite part of Gold/Green Dye Spires"},
{name: "Chart", island: "Iridescent Island", obt: "Yes", location: "Often found near Magma."},
{name: "Sandstone", island: "Iridescent Island", obt: "Yes", location: "Often found near Magma"},
{name: "Lava", island: "Iridescent Island", obt: "Yes", location: "Often found near Magma"},
{name: "Burning Rock", island: "Iridescent Island", obt: "-", location: "Often found in/near Magma"},
{name: "Earth Pile", island: "Iridescent Island", obt: "-", location: "Found on Earth near Sea Level, near hills"},
{name: "Rock Pile", island: "Iridescent Island", obt: "-", location: "Found on Earth near Sea Level, near hills"},
{name: "Singed Shrub", island: "Iridescent Island", obt: "-", location: "Found on Earth hills without Coal, but with Obsidian"},
{name: "Sandwort", island: "Iridescent Island", obt: "-", location: "Sometimes found on Earth hills without Coal, but with Obsidian"},
{name: "Animal Bones", island: "Iridescent Island", obt: "-", location: "Usually found on Earth near Sea Level, particularly near the sea"},
{name: "Small Stones", island: "Iridescent Island", obt: "-", location: "Common near Sea Level"},
{name: "Big Rock", island: "Iridescent Island", obt: "-", location: "Somewhat common near Sea Level"},
{name: "Slimespawn", island: "Iridescent Island", obt: "-", location: "Generally found on Dark Dolomite near Sea Level"},
{name: "Cow", island: "Iridescent Island", obt: "-", location: "Livestock"},
{name: "Merchant", island: "Iridescent Island", obt: "-", location: "-"},
{name: "Miner", island: "Iridescent Island", obt: "-", location: "-"},
{name: "Arid Earth", island: "Sunny Sands", obt: "Yes", location: "Found in various sections of Desert"},
{name: "Sandy Sandstone", island: "Sunny Sands", obt: "Yes", location: "Common in Deserts"},
{name: "Stony Soil", island: "Sunny Sands", obt: "Yes", location: "Found in Earth Hills"},
{name: "Coal Vein", island: "Sunny Sands", obt: "-", location: "First Underground Layer"},
{name: "Blue Dye Vein", island: "Sunny Sands", obt: "-", location: "Third (common) and Fourth (rare) Underground Layer"},
{name: "Diamond Vein", island: "Sunny Sands", obt: "-", location: "Fourth Underground Layer, hidden in a small pyramid topped by a Gold Vein"},
{name: "Pampas Grass", island: "Sunny Sands", obt: "-", location: "Found on Earth Hills"},
{name: "Marshroom", island: "Sunny Sands", obt: "-", location: "Found in the First Underground Layer"},
{name: "Massive Mushroom Cap", island: "Sunny Sands", obt: "Yes", location: "Found in Third Underground Layer"},
{name: "Supermassive Mushroom Cap", island: "Sunny Sands", obt: "Yes", location: "Found in Third Underground Layer"},
{name: "Massive Mushroom Stem", island: "Sunny Sands", obt: "Yes", location: "Found in Third Underground Layer"},
{name: "Stalagmites", island: "Sunny Sands", obt: "-", location: "Found in Fourth Underground Layer"},
{name: "Sizable Stalagmite", island: "Sunny Sands", obt: "-", location: "Found in Fourth Underground Layer"},
{name: "Vineapple", island: "Sunny Sands", obt: "-", location: "Found in Underground Layers"},
{name: "Shineapple", island: "Sunny Sands", obt: "-", location: "Found in Underground Layers"},
{name: "Glumgus", island: "Sunny Sands", obt: "-", location: "Found in the Third Underground Layer"},
{name: "Iron Vein", island: "Sunny Sands", obt: "-", location: "Second Underground Layer"},
{name: "Malachite", island: "Sunny Sands", obt: "Yes", location: "Found in Third Underground Layer"},
{name: "White Dye Vein", island: "Sunny Sands", obt: "-", location: "Third Underground Layer"},
{name: "Mythril Vein", island: "Sunny Sands", obt: "-", location: "Fourth Underground Layer, hidden in a small pyramid topped by a White Dye Vein"},
{name: "Big Palm Tree", island: "Sunny Sands", obt: "-", location: "Sometimes near Lakes"},
{name: "Banana", island: "Sunny Sands", obt: "-", location: "Sometimes near Lakes"},
{name: "Gladiolus", island: "Sunny Sands", obt: "-", location: "Found near Lakes"},
{name: "Fibrous Fern", island: "Sunny Sands", obt: "-", location: "Found near Lakes"},
{name: "Cactus Crown", island: "Sunny Sands", obt: "-", location: "Common in Deserts, top piece"},
{name: "Cactus Trunk", island: "Sunny Sands", obt: "-", location: "Common in Deserts, bottom and middle pieces"},
{name: "Prickly Peach Cactus", island: "Sunny Sands", obt: "-", location: "Found in Deserts"},
{name: "Sweetcorn", island: "Sunny Sands", obt: "-", location: "Found on Earth Hills, Tilled Soil"},
{name: "Sunflowers", island: "Sunny Sands", obt: "-", location: "Found on hills (Earth)"},
{name: "Fan Fern", island: "Sunny Sands", obt: "-", location: "Found near Lakes"},
{name: "Chili Pepper", island: "Sunny Sands", obt: "-", location: "Found on Arid Earth Deserts"},
{name: "Cat", island: "Sunny Sands", obt: "-", location: "Pet"},
{name: "Dancer (M)", island: "Sunny Sands", obt: "Cottontail Costume", location: "-"},
{name: "Bartender (M)", island: "Sunny Sands", obt: "Blue and white ?", location: "-"},
{name: "Dancer (F)", island: "Sunny Sands", obt: "Cottontail Costume", location: "Lower?"},
{name: "Snow", island: "Rimey Reef", obt: "-", location: "Easily found in most Snowfield based areas."},
{name: "Witchgrassy Earth", island: "Rimey Reef", obt: "-", location: "Found near Sea Level in small patches"},
{name: "Battlefield Earth", island: "Rimey Reef", obt: "-", location: "Sometimes found near Witchgrassy Earth"},
{name: "Ice", island: "Rimey Reef", obt: "-", location: "Easily found in beach areas"},
{name: "Yellow Dye Vein", island: "Rimey Reef", obt: "-", location: "Found in some short Hills, visible from sides"},
{name: "Pink Dye Vein", island: "Rimey Reef", obt: "-", location: "Found in and near Tall Mountain Spas"},
{name: "Snowy Cedar", island: "Rimey Reef", obt: "-", location: "Mountaintops"},
{name: "Big Snowy Cedar", island: "Rimey Reef", obt: "-", location: "Mountaintops"},
{name: "Cedar Stump", island: "Rimey Reef", obt: "-", location: "Break a Cedar, may rarely spawn naturally"},
{name: "Potato", island: "Rimey Reef", obt: "-", location: "Near sea level Snow, possibly more common near Witchgrassy Earth, Tilled Soil"},
{name: "Ice Lolly", island: "Rimey Reef", obt: "Yes", location: "Found inside Ice huts/pyramids on Ice fields"},
{name: "Border Boulder", island: "Rimey Reef", obt: "Yes", location: "Tall Mountain Spas"},
{name: "Big Border Boulder", island: "Rimey Reef", obt: "Yes", location: "Tall Mountain Spas"},
{name: "Floating Flower Petals", island: "Rimey Reef", obt: "-", location: "Tall Mountain Spas, 3 per Spa"},
{name: "Spa Spout", island: "Rimey Reef", obt: "Yes", location: "Tall Mountain Spas, 1 per Spa"},
{name: "Bathing Stool", island: "Rimey Reef", obt: "Yes", location: "Tall Mountain Spas, 1 per Spa."},
{name: "Broken Stone Wall", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Torched Tree", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Burnt Branch", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Knight Oddments", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Banner of Hargon", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Tattered Banner of Erdrick", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Splinters", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Pebbles", island: "Rimey Reef", obt: "-", location: "Found near Sea Level, often near Witchgrassy Earth"},
{name: "Magic Outcrop", island: "Rimey Reef", obt: "-", location: "Found in Snowfields, often near Witchgrassy Earth"},
{name: "Scarletulip", island: "Rimey Reef", obt: "-", location: "Sometimes found on Battlefield Earth"},
{name: "Snowman", island: "Rimey Reef", obt: "Yes", location: "Sometimes Found at Ice Fields"},
{name: "Leek", island: "Rimey Reef", obt: "-", location: "Found near Block Trees, Tilled Soil"},
{name: "Freezia", island: "Rimey Reef", obt: "-", location: "Found in Snowfields"},
{name: "Dark Bark", island: "Rimey Reef", obt: "-", location: "Found on Block Trees"},
{name: "Teal Leaves", island: "Rimey Reef", obt: "-", location: "Found on Block Trees"},
{name: "Leak", island: "Rimey Reef", obt: "Leak*, Leak Seed", location: "Found on steppes near block trees"},
{name: "Soldier", island: "Rimey Reef", obt: "-", location: "-"},
{name: "Soldier", island: "Rimey Reef", obt: "-", location: "-"},
{name: "Marble", island: "laguna perfuma", obt: "Yes", location: "Found in the Snow hills next to the beach"},
{name: "Purple Dye Vein", island: "laguna perfuma", obt: "-", location: "Found in Lake islands topped by Holyhock"},
{name: "Vault Wall", island: "laguna perfuma", obt: "Yes", location: "Ruins"},
{name: "Viny Vault Wall", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Masonry Wall", island: "laguna perfuma", obt: "Yes", location: "Ruins"},
{name: "Cracked Vault Wall", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Broken Masonry", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Classic Column Capital", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Classic Column Midsection", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Classic Column Pedestal", island: "laguna perfuma", obt: "-", location: "Ruins"},
{name: "Purplotus", island: "laguna perfuma", obt: "-", location: "Found on Lake islands topped by Holyhock"},
{name: "Heatroot", island: "laguna perfuma", obt: "-", location: "Found in shallow Lake water, Water covered Tilled Soil"},
{name: "Butterbeans", island: "laguna perfuma", obt: "-", location: "Found near Lake water, Tilled Soil"},
{name: "Holyhock", island: "laguna perfuma", obt: "-", location: "Found on Lake islands topped by Holyhock"},
{name: "Oversized Shrub", island: "laguna perfuma", obt: "Yes", location: "Found on Lake islands topped by Holyhock"},
{name: "Black Dye Vein", island: "laguna perfuma", obt: "-", location: "Found on Lake islands topped by a Big Silver Birch Tree"},
{name: "Big Silver Birch Tree", island: "laguna perfuma", obt: "-", location: "Meadows"},
{name: "Silver Birch Tree", island: "laguna perfuma", obt: "-", location: "Meadows"},
{name: "Silver Birch Stump", island: "laguna perfuma", obt: "-", location: "Found in Meadows."},
{name: "Blackbell", island: "laguna perfuma", obt: "-", location: "Found on Lake islands topped by a Big Silver Birch Tree"},
{name: "Melon", island: "laguna perfuma", obt: "-", location: "Meadows, often near snow, Tilled Soil"},
{name: "Rose", island: "laguna perfuma", obt: "-", location: "Ruins, Top of Vines"},
{name: "Pumice", island: "laguna perfuma", obt: "-", location: "Found on Snow hills"},
{name: "Splashing Stone", island: "laguna perfuma", obt: "Yes", location: "Found in Waterfalls structures in lakes/rivers"},
{name: "Wisteria Crown", island: "laguna perfuma", obt: "-", location: "Meadows, Found on Block Tree-like objects"},
{name: "Wisteria Stem", island: "laguna perfuma", obt: "-", location: "Meadows, Found on Block Tree-like objects"},
{name: "Wisteria Root", island: "laguna perfuma", obt: "-", location: "Meadows, Found on Block Tree-like objects"},
{name: "Lush Leaves", island: "laguna perfuma", obt: "-", location: "Meadows, Found on Block Tree-like objects"},
{name: "Leaves", island: "laguna perfuma", obt: "-", location: "Meadows, Found on Block Tree-like objects"},
{name: "Sheep", island: "laguna perfuma", obt: "-", location: "Livestock"},
{name: "Butterbeans", island: "laguna perfuma", obt: "Butterbeans*, Butterbean Sprout", location: "Found on Grassy Earth, near water."},
{name: "Nun", island: "laguna perfuma", obt: "-", location: "Blue Uniform"},
{name: "Elder (M)", island: "laguna perfuma", obt: "-", location: "Blue Uniform"},
{name: "Elder (F)", island: "laguna perfuma", obt: "-", location: "Brown Robe"},
{name: "Child (F)", island: "laguna perfuma", obt: "-", location: "Red and White clothes"},
{name: "Child (M)", island: "laguna perfuma", obt: "-", location: "Blue and White clothes"},
{name: "Seaside Sand", island: "Coral Cay", obt: "-", location: "Common in the beach area"},
{name: "Stony Sand", island: "Coral Cay", obt: "-", location: "Common in the beach area"},
{name: "Seaside Seaweed", island: "Coral Cay", obt: "-", location: "Found in Beach Area"},
{name: "Seaweed Stack", island: "Coral Cay", obt: "-", location: "Found in Beach Area"},
{name: "Coneconut Tree", island: "Coral Cay", obt: "-", location: "Found in Beach Area"},
{name: "Bigonia", island: "Coral Cay", obt: "-", location: "Found in Beach Area"},
{name: "Clam Shell", island: "Coral Cay", obt: "-", location: "Underwater, relatively common, easily located by bubbles"},
{name: "Seaweed", island: "Coral Cay", obt: "-", location: "Underwater, mainly in shallow depths"},
{name: "Colossal Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "White Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Black Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Deep Depths, near Rubies/Gold Veins"},
{name: "Purple Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Red Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Green Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Yellow Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Blue Coral Colony", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Gold Vein", island: "Coral Cay", obt: "-", location: "Water, Deep Depths"},
{name: "Ruby Vein", island: "Coral Cay", obt: "-", location: "Water, Deep Depths"},
{name: "Driftwood", island: "Coral Cay", obt: "-", location: "Underwater, Shallow Depths"},
{name: "Driftlumber", island: "Coral Cay", obt: "-", location: "Underwater, Shallow Depths"},
{name: "Scallywinkle", island: "Coral Cay", obt: "-", location: "Underwater, Shallow Depths"},
{name: "Seaslime Shell", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Capsized Crate", island: "Coral Cay", obt: "-", location: "Underwater, Shallow Depths"},
{name: "Broken Barrel", island: "Coral Cay", obt: "-", location: "Water, Deep Depths"},
{name: "Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "White Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Black Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Mid/Deep Depths, near Rubies/Gold Veins"},
{name: "Purple Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Red Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Green Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Yellow Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Blue Coral", island: "Coral Cay", obt: "Yes", location: "Underwater, Shallow Depths"},
{name: "Ash", island: "Defiled Isle", obt: "Yes", location: "Common Block, Looks similar to Bonestone, but does not have a skull."},
{name: "Magnetite Vein", island: "Defiled Isle", obt: "-", location: "Found in Ash as groups of"},
{name: "Bloodstone", island: "Defiled Isle", obt: "Yes", location: "Found as large hills"},
{name: "Witchgrassy Earth", island: "Defiled Isle", obt: "-", location: "Found in patches of Ash Tiles."},
{name: "Poisonous Peat", island: "Defiled Isle", obt: "Yes", location: "Found around Poison"},
{name: "Blighted Branch", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Dragon Bones", island: "Defiled Isle", obt: "Yes", location: "Found on Ash"},
{name: "Dead Tree", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Tainted Tree", island: "Defiled Isle", obt: "-", location: "Found in Poison"},
{name: "Twisted Tree Trunk", island: "Defiled Isle", obt: "-", location: "Usually in or near Poison"},
{name: "She-Slimespawn", island: "Defiled Isle", obt: "-", location: "Found on Bloodstone"},
{name: "Frogstool", island: "Defiled Isle", obt: "-", location: "Found on Ash, near Dead Trees"},
{name: "Colossal Crag", island: "Defiled Isle", obt: "-", location: "Found on Ash or Mountains"},
{name: "Crag", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Tingleweed", island: "Defiled Isle", obt: "-", location: "Can be found on top of Ash hills - inflicts paralyze"},
{name: "Orichalcum Vein", island: "Defiled Isle", obt: "-", location: "Found in Poison pools surrounded by Obsidian"},
{name: "Chalk", island: "Defiled Isle", obt: "Yes", location: "Found on Mountains"},
{name: "Chunky Chalk", island: "Defiled Isle", obt: "Yes", location: "Found on Mountains."},
{name: "Septic Shrub", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Witchgrassy Plant", island: "Defiled Isle", obt: "-", location: "Found on Poisonous Peat"},
{name: "Bogwort", island: "Defiled Isle", obt: "-", location: "Found on Poisonous Peat, generally near large Poison pools"},
{name: "Tattered Standard", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Tattered Tent", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Broken Barricade", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Dilapidated Crate", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Bonfire", island: "Defiled Isle", obt: "Yes", location: "Found on Ash"},
{name: "Shadowgrass", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Pongsettia", island: "Defiled Isle", obt: "Yes", location: "Found near Poison"},
{name: "Infernal Ivy", island: "Defiled Isle", obt: "-", location: "Found on the sides of Mountains."},
{name: "Pebble Pile", island: "Defiled Isle", obt: "-", location: "Found on Ash"},
{name: "Singer/Diva", island: "Defiled Isle", obt: "-", location: "White Dress"},
{name: "Chert", island: "Unholy Holm", obt: "Yes", location: "Common in the outer area."},
{name: "Spoiled Soil", island: "Unholy Holm", obt: "-", location: "Can be found near Scales"},
{name: "Strange Sand", island: "Unholy Holm", obt: "-", location: "Found in desert-like areas"},
{name: "Scales", island: "Unholy Holm", obt: "-", location: "Found in Scale tiles"},
{name: "Small Stones", island: "Unholy Holm", obt: "-", location: "Can be found in desert-like areas"},
{name: "Wide Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows on the sides of Sanguine Cinders"},
{name: "Small Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows on the sides of Sanguine Cinders"},
{name: "Long Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows on the sides of Sanguine Cinders"},
{name: "Floating Fragments", island: "Unholy Holm", obt: "-", location: "Often found on top of mountains"},
{name: "Blooming Poxglove", island: "Unholy Holm", obt: "Yes", location: "Found near Sanguine Sand"},
{name: "Budding Poxglove", island: "Unholy Holm", obt: "Yes", location: "Can be found on the sides of Sanguine Sand"},
{name: "Upward-Pointing Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows below Sanguine Sand, Floating Scale Structures"},
{name: "Downward-Pointing Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows near Sanguine Cinders"},
{name: "Vertical Vile Vines", island: "Unholy Holm", obt: "-", location: "Grows near Sanguine Sand, Floating Scale Structures"},
{name: "Sanguine Cinders", island: "Unholy Holm", obt: "Yes", location: "Found in some floating blocks and Mountains"},
{name: "Sanguine Sand", island: "Unholy Holm", obt: "Yes", location: "Found in some floating blocks"},
{name: "Sanguine Sandy Sandstone", island: "Unholy Holm", obt: "Yes", location: "Common"},
{name: "Sanguine Sandstone", island: "Unholy Holm", obt: "Yes", location: "Common"},
{name: "Obsidian", island: "Unholy Holm", obt: "-", location: "Can be found near Scales"},
{name: "Terrible Talon", island: "Unholy Holm", obt: "Yes", location: "Found on Scales"},
{name: "Twisting Tail", island: "Unholy Holm", obt: "Yes", location: "Found on Scales"},
{name: "Enormous Eyeball", island: "Unholy Holm", obt: "Yes", location: "Found in floating Plasma Scale Structures"},
{name: "Titanic Top Teeth-", island: "Unholy Holm", obt: "Yes", location: "Found under Floating Scale Structures"},
{name: "Big Bad Bottom Teeth", island: "Unholy Holm", obt: "Yes", location: "Found on Grounded Scale Structures."},
{name: "Huge Horn", island: "Unholy Holm", obt: "Yes", location: "Found on Grounded Scale Structures."},
{name: "Humongous Horn", island: "Unholy Holm", obt: "Yes", location: "Found on Floating Scale Structures"},
{name: "Freakish Fin", island: "Unholy Holm", obt: "Yes", location: "Found near Enormous Eyeballs and other Scale Structures"},
{name: "Bones", island: "Unholy Holm", obt: "Yes", location: "Can be found near Desert areas"},
{name: "Bard", island: "Unholy Holm", obt: "-", location: "Feathered Hat"}
]